### ISSUE TITLE
Set position of camera from World Overview

### ISSUE THREAD

**Issue by cybergeek94** [llbit/chunky#143]
Since the preview requires a lot of CPU power to render in near-realtime, navigation within the preview can be very time consuming and frustrating due to the lag.

It would be very helpful if it were possible to set the location of the camera from the World Overview (where chunks are selected for loading), possibly with a shift-right-click or a button in the render controls that when clicked, tells the World Overview canvas that the next click it receives should set the camera location instead of selecting/deselecting a chunk.

**Comment by llbit** [comment]
This was fixed in 955d5d9e117aa2f43622f1f042c018afc198c477

The feature will be shipped in the next release (1.3.5).
