### ISSUE TITLE
'Camera Shift' enhancement

### ISSUE THREAD

**Issue by DaedalusYoung** [llbit/chunky#178]
For a lot of renders, often architectural, but also applies to others, you will want to keep the camera rotation relative to the ground at 0, so vertical lines are parallel.

You can do this now of course, but then your framing will be wrong. You will either need to render a much larger image than necessary, then cut off the bottom half in post-pro later, but that wastes a lot of render time.

Irl, photographers do this with a lens on a bellow, tilting and shifting it until the vertical lines are parallel (which is also where tilt/shift comes from). In cg images, there often is a camera shift feature. In Blender for example, it is on the Camera's Object Data tab, named Shift.

It would be great if this could be added to Chunky.

Some examples of renders that would've been better with a shifted camera:
- http://www.reddit.com/r/chunky/comments/1ktman/early_autumn_harvest_how_do_you_like_it_3840_x/
- http://www.reddit.com/r/chunky/comments/1kb0ng/the_hotel/
- http://www.reddit.com/r/chunky/comments/1k2xo5/downtown_greasy_springs_15_complete/

**Comment by leMaik** [comment]
This is now implemented via two text fields under _Orientation and position_. The values are relative to the height of the image (e.g. 1 will shift the camera by the image height).

|change orientation|lense shift|
|---|---|
|![no-tilt-shift](https://user-images.githubusercontent.com/5544859/79383211-18a34880-7f65-11ea-91ad-791796c60d18.png)|![tilt-shift](https://user-images.githubusercontent.com/5544859/79383239-2658ce00-7f65-11ea-8676-44f926550a92.png)|
