### ISSUE TITLE
Y cutoff text message request.

### ISSUE THREAD

**Issue by Dominic001** [llbit/chunky#298]
Could it be possible to show a small popup message when trying to change the y cutoff that a reload of the chunks is necessary? The first time i used 1.3.4 there was there was this y cutoff, and I had to switch back to 1.3.2 because I thougt that it was a bug that the render scene didnt update after changing the y cutoff bar. Maybe many other chunky users have had this experience too.

**Comment by llbit** [comment]
Thanks for the suggestion, it seems like a good thing to add!
