### ISSUE TITLE
The id of the stairs is incorrect if there are two stairs facing each other

### ISSUE THREAD

**Issue by Autopoietico** [llbit/chunky#300]
In this two images is possible see the diference between the render and the original map structure:
![2015-01-19_04 39](https://cloud.githubusercontent.com/assets/8708366/5798529/05ff7780-9f96-11e4-8df6-f182963943e0.png)
![windsurf-ironfarm-1550](https://cloud.githubusercontent.com/assets/8708366/5798534/0c8d2048-9f96-11e4-99c5-e47d9ae6cb3e.png)
Two stairs facing each other make that one of the stairs use a incorrect id in the render.

**Comment by llbit** [comment]
Interesting bug. I'll check this out. Which version of Minecraft and which version of Chunky were you using?

**Comment by Autopoietico** [comment]
Minecraft 1.8 and Chunky 1.3.4
