### ISSUE TITLE
Support for multiplayer worlds 

### ISSUE THREAD

**Issue by pokeball99** [llbit/chunky#307]

**Comment by seaside98** [comment]
Not possible. You might want to look into [world downloader](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285484-world-downloader-mod).

**Comment by llbit** [comment]
Multiplayer worlds do work if you have access to the server. You just have to point Chunky to the world directory where the server world is stored.

**Comment by pokeball99** [comment]
it should be possible,https://miners-movies.com can go into the server in real-time and record all movments and info
