### ISSUE TITLE
Chunky stops rendering for no reason

### ISSUE THREAD

**Issue by luminoso** [llbit/chunky#309]
Steps to reproduce:
1) Start a new scene
2) Let it run
3) Eventually it will stop render

No error messages. It just hangs (cpu load also stops). GUI says "Rendering: 488 of 15.000", ETA, render time also stops updating

Tested with chunky version 1.3.5-alpha4 and 1.3.4, running Archlinux 64bit, java version 1.8.0_31.

I tested deleting .chunky directory and recreate the scene from scratch. Didn't help.

**Comment by llbit** [comment]
Hi! Thanks for the bug report!

Does this happen with different scenes or only one particular scene? If it only happens in one scene it might be a rendering issue with some feature in the scene, so please try another region in your world or just another world.
