### ISSUE TITLE
Chunky not loading chunks all the way

### ISSUE THREAD

**Issue by Flash12** [llbit/chunky#310]
Been having an issue with Chunky for a few months in that it will only render the top half of a build if it's anything taller than a house. This was an attempt to render a tower. I've redone the world a few times just to see if I didn't download the chunks properly or save the world right but still comes out like this. Happened with a cathedral as well.
![rjmpvm4](https://cloud.githubusercontent.com/assets/11202830/6383701/7313ec22-bd21-11e4-805b-c9ec0fa13155.png)

**Comment by Flash12** [comment]
Nvm I figured out the issue. Seems there's a tab called "Y Cutoff" which was the issue. Set it to 0 and it works fine now.

**Comment by llbit** [comment]
Closing this issue because it resolved itself!
