### ISSUE TITLE
Light Errors

### ISSUE THREAD

**Issue by TheDarkWarLord** [llbit/chunky#312]
When I try to make renders with light sources in it this happens
http://prntscr.com/6nqaqv I used the latest (1.3.4 version).
(no april fools)

**Comment by llbit** [comment]
From the FAQ (http://chunky.llbit.se/faq.html):

> Torches and other small light sources cause a very random illumination and it takes many samples per pixel to render such light smoothly. For more information see the Path Tracing article! You can disable emitters under the Lighting tab in the Render Controls dialog to remove the random bright dots. Note that rendering for a longer time will eventually remove the dots as the render approaches the expected value.

It is not a bug, just an effect of the algorithm used in the rendering.
