### ISSUE TITLE
Steps are not rendered well in 1.3.5

### ISSUE THREAD

**Issue by lact339** [llbit/chunky#318]
With the new update there is a problem with rendering steps. Didn't happend with 1.3.4.
Steps are not rendered. They are there, and in 1.3.4. everything worked fine. I know there are changes with the steps, so I think the problem can occur. Please fix it. :)
![steps](https://cloud.githubusercontent.com/assets/12222650/7445802/49414d4c-f1c2-11e4-85ea-a994c0511713.png)

**Comment by llbit** [comment]
Does the issue persist after reloading the chunks?

**Comment by llbit** [comment]
I believe this is fixed. If you can reproduce the issue in the latest version of Chunky please post a follow up comment.
