### ISSUE TITLE
World Saves Directory Problem

### ISSUE THREAD

**Issue by Maufacurw** [llbit/chunky#324]
I am asked to select the directory where my worlds are stored, I do this, and I am told that it is an invalid directory? I know that i am selecting the correct one too.

**Comment by Martynus** [comment]
Which OS are you on? Could you show which directory you select? Are there any worlds in the world directory you select?

**Comment by Maufacurw** [comment]
Windows 7, as for the other two questions, i'm not sure

**Comment by llbit** [comment]
This should be fixed in Chunky 1.4.0. Please post a follow up comment if you still have this problem.
