### ISSUE TITLE
Water world + fog creates sharp horizon border.

### ISSUE THREAD

**Issue by GolonkaSwe** [llbit/chunky#326]
1.3.5
A sharp border is visible at the horizon when combining water world with the new fog options.

http://i.imgur.com/NHV9CYL.png
(top half of a 4k render)

This bug was fixed in 1.3.4 already, when there wasn't a fog slider.

**Comment by llbit** [comment]
Interesting. Will take a look at this.

**Comment by llbit** [comment]
I am not able to reproduce this issue. What fog density setting were you using in that scene?

**Comment by GolonkaSwe** [comment]
{
  "sdfVersion": 5,
  "name": "bro3-July-Downtown-1",
  "width": 3840,
  "height": 2160,
  "exposure": 0.8858667904100824,
  "postprocess": 1,
  "renderTime": 7580238,
  "spp": 334,
  "sppTarget": 1000,
  "rayDepth": 5,
  "pathTrace": true,
  "dumpFrequency": 500,
  "saveSnapshots": false,
  "emittersEnabled": false,
  "emitterIntensity": 13.0,
  "sunEnabled": true,
  "stillWater": false,
  "waterOpacity": 0.42,
  "waterVisibility": 9.0,
  "useCustomWaterColor": false,
  "fogColor": {
    "red": 0.42814502293337064,
    "green": 0.5858024691358026,
    "blue": 1.0
  },
  "fastFog": true,
  "biomeColorsEnabled": true,
  "transparentSky": false,
  "fogDensity": 3.0E-4,
  "waterHeight": 63,
  "world": {
    "path":
    "dimension": 0
  },
  "camera": {
    "position": {
      "x": 382.6777074998721,
      "y": 245.399123060053,
      "z": 2489.521906338583
    },
    "orientation": {
      "roll": 0.0,
      "pitch": -1.3365071449543777,
      "yaw": -0.7955058499679388
    },
    "projectionMode": "PINHOLE",
    "fov": 28.45987618184191,
    "dof": "Infinity",
    "focalOffset": 2.0
  },
  "sun": {
    "altitude": 0.32675713063653233,
    "azimuth": 4.101523742186675,
    "intensity": 1.575024977871781,
    "color": {
      "red": 0.9666444444444444,
      "green": 0.6906711111111112,
      "blue": 0.506688888888889
    }
  },
  "sky": {
    "skyYaw": 0.0,
    "skyMirrored": true,
    "skyLight": 0.7619598847985166,
    "mode": "SIMULATED",
    "horizonOffset": 0.1,
    "cloudsEnabled": false,
    "cloudSize": 64.0,
    "cloudOffset": {
      "x": 0.0,
      "y": 128.0,
      "z": 0.0

**Comment by GolonkaSwe** [comment]
The density setting doesn't matter unless it's off or so high you can't see the scene anyway, at around 0,001 or lower is good.
I always see this border when looking towards infinite ocean or the horizon and having fog turned on.

It's also there when looking at infinite ocean and having transparent sky on, it appears more transparent beyond the border as if the skybox floor ended.
Here's an example of that: http://i.imgur.com/y5z9FjF.png

**Comment by llbit** [comment]
Here is a render I did to try to reproduce, with fog density 0.0017:

![14w27b4-1000](https://cloud.githubusercontent.com/assets/2757386/9838583/a9b436dc-5a61-11e5-87f6-68a288ac2713.png)

I will try with a lower density setting.

**Comment by GolonkaSwe** [comment]
Ok I found a way to replicate it.
http://imgur.com/a/TvvlN
I don't know about you but that kinda speaks for itself.
Having lots of ocean space between your selections makes a box like that it seems.

**Comment by llbit** [comment]
Ok, cool. I was able to reproduce it also. This seems to be an octree sizing issue: the water plane is incorrectly positioned relative to the chunks in the octree.

**Comment by llbit** [comment]
The transparent water is unrelated to this issue by the way. The reason I made water transparent is because I thought waterfalls should show a bit of the sky behind them, but it does not work well with the water world option because then there is no seabed under the infinite water plane.

**Comment by GolonkaSwe** [comment]
That makes sense. 
And that was a quick fix, appreciate your dedication! Can't wait for the next version.
