### ISSUE TITLE
Rendering stops without error or crash

### ISSUE THREAD

**Issue by TheCrunchy** [llbit/chunky#330]
I am having an issue where rendering will just stop and continue to say "Rendering 543 of 7000" but will just stay frozen on that frame for hours, i have had this issue on 3 different worlds. 

I am using an AMD CPU and using the latest version of Chunky from the launcher.

**Comment by llbit** [comment]
Does this happen with other scenes or just one particular scene? Can you upload the scene somewhere and send me a link so I can try to reproduce this?
