### ISSUE TITLE
Chunky Wont let me Allocate more RAM

### ISSUE THREAD

**Issue by ritzbitz69** [llbit/chunky#332]
Anytime i attempt to give chunky more RAM to render faster it Gives me this error: Error occurred during initialization of VM
Could not reserve enough space for 1560576KB object heap
Chunky exited abnormally with exit value 1
 I have 16Gbs of RAM so i should easily be able to allocate more to it, i have tried updating java and it didnt help. I cant allocate more RAM To minecraft itself so i have no idea whats going on. This is also the same error i get when trying to allocate more RAM to a server im hosting.

**Comment by Redmonkey1313** [comment]
I'm getting that same error code:(

**Comment by marcbal** [comment]
Maybe you have a 32bit version of Java or a 32bit version of your OS.

**Comment by ritzbitz69** [comment]
No, I can assure you I have a 64 bit on Both versions

**Comment by marcbal** [comment]
Do you have ONLY 64 bit version of Java, or have you 64 and 32bit version installed ?

**Comment by ritzbitz69** [comment]
I only have 64 bit installed.

**Comment by llbit** [comment]
I am closing this issue because it has been inactive for a while.
