### ISSUE TITLE
There is white floor but no sky in my render view

### ISSUE THREAD

**Issue by Maxreal** [llbit/chunky#343]
After I creat 3d scene, I can see  my chunks are surrended by a white floor with a ruled grid of horizontal and vertical line. just like the attachment picture shows. It just feels like there is a infinite white grid plane on the floor. and if you look up, you'll find the sky is below the floor.
![qq 20151128123356](https://cloud.githubusercontent.com/assets/16054825/11450121/20bf7aec-95cd-11e5-914d-314032d3bdec.png)
![qq 20151128123549](https://cloud.githubusercontent.com/assets/16054825/11450122/20c307f2-95cd-11e5-87d6-01d7ee9f70b5.png)

**Comment by Maxreal** [comment]
Is anyone help me ? I mean how can I hide the horizon that appear white here??? with this white horizon, I can't see any sky if my camera is looking from top to down!!!! anyone here?

**Comment by imBizink** [comment]
When you start the render, that grid will become sky, it is just used in the preview to show empty chunks and does not show in the final product. :)

**Comment by llbit** [comment]
I second the answer from @imBizink, and since this issue has been inactive for a long time I will close this. Please post a follow up reply if you still need help.
