### ISSUE TITLE
Render only part of the scene with a lot of noise

### ISSUE THREAD

**Issue by marcbal** [llbit/chunky#344]
Some render are very long just because of some part of the scene with a lot of noise.
Is it possible to find a way to render only this part when there is no need to continue rendering the rest of the image ?

**Comment by empirebuilder1** [comment]
That's not how the raytracing engine works. 

Turn off emitters if you want shorter render times.

**Comment by marcbal** [comment]
Why the raytracing couldn't  work only on a part of the image? 

Each pathtrace is only for 1 pixel of the rendering. So, it is possible to select a part of the rendering image, where the pathtracing continue to work, and ignore the pixels outside this chunk of the image.

It's just a suggestion, and I know that removing emitters will reduce the render time. But it's not what I want.

**Comment by empirebuilder1** [comment]
It's not how the *current* engine works. While it might be possible, it'd require a change to how it merges the calculations.  

Actually on a second, less personal anger fueled check, it might not be quite such a bad idea. However, emitters (relatively) close to the camera tend to scatter light across the entire scene, and probably would only be effective later on in a render.

**Comment by leMaik** [comment]
This pretty much duplicates #150, so I'll close it. With a few changes to the way that SPP are stored (per pixel instead of globally), this should be possible to implement.

**Comment by sn0wyfall** [comment]
@leMaik Are there any plans on implementing this on the roadmap?

**Comment by leMaik** [comment]
@sn0wyfall This is closed as a duplicate, please keep an eye on #150 for updates. :-)
