### ISSUE TITLE
Blocks won't load

### ISSUE THREAD

**Issue by jcr0522** [llbit/chunky#351]
Whenever I create a new scene, the blocks won't load in the preview. I see signs, but no blocks. Am I using this incorrectly, or is this a bug?

System Details:

iMac
Intel i5 2.7 GHz
NVIDIA GeForce GT 640M 512 MB
8 GB of Ram

Thank you!

**Comment by empirebuilder1** [comment]
Did you select chunks from a world in the Chunky main window before creating a scene?

**Comment by llbit** [comment]
Closing this issue because it seems inactive.
