### ISSUE TITLE
Pressing new scene does not create a pop up

### ISSUE THREAD

**Issue by edgijex** [llbit/chunky#353]
Chunky worked great for two days. Then for no reason it stopped loading maps when i click new scene.

**Comment by llbit** [comment]
I don't know what causes this, can't really help without being able to reproduce the bug.

**Comment by llbit** [comment]
The UI has been rewritten now, so whatever issues you were having previously will likely be solved in the next release (1.4.0).

Please check if you still have the issue in the 1.4.0 snapshot and reply if you need more help. Thank you!
