### ISSUE TITLE
White Screen on opening Render Preview Window

### ISSUE THREAD

**Issue by Sunlost** [llbit/chunky#362]
Whenever I open the preview window, it's entirely white. http://i.pxl.lt/kXdN5H

OS: Windows 8.1
Chunky Version: 1.3.8

I'm not sure what additional information you may need, but I'm happy to provide it.

**Comment by llbit** [comment]
I think this should be fixed in the latest 1.4.0 snapshot, and it should be fixed in the 1.4.0 release.
