### ISSUE TITLE
Request - implement 360 VR projection

### ISSUE THREAD

**Issue by jason-green-io** [llbit/chunky#364]
According to this: https://developers.google.com/cardboard/jump/rendering-ods-content.pdf

**Comment by leMaik** [comment]
This idea is awesome! I started to implement this some hours ago and it's alreay working. Just need to add some GUI elements and then I'll send a PR. :+1:

**Comment by jason-green-io** [comment]
Ohhhhh, I can't wait to play with this!

The way you implemented it you have to generate left and right and then
stitch them together outside Chunky, correct?

**Comment by leMaik** [comment]
@jason-green-io Exactly. You have to render one image with the _ODS (left eye)_ projection mode and one with _ODS (right eye)_ and then join them.
Example image: https://lemaik.github.io/rs-sphere/

Self advertising: You can use [rs-sphere](https://github.com/leMaik/rs-sphere/] to display ODS images in your browser, with gyro support and all.
