### ISSUE TITLE
Holding SHIFT in "Render Preview" window for moving at 1/10 of normal distance not working

### ISSUE THREAD

**Issue by electronrussia** [llbit/chunky#374]
I think that BUG in af5d235 when checking ChunkyFrame.this.getFocusOwner(). That fixes problems described in af5d235 commit, but creating problems with "Render Preview" window. Moving at 1/10 of normal distance now not working.

**Comment by empirebuilder1** [comment]
Confirmed in 1.3.8. Holding shift doesn't affect the speed of camera movement.
