### ISSUE TITLE
Chunky doesn't render Bone blocks

### ISSUE THREAD

**Issue by godleydemon** [llbit/chunky#375]
It also doesn't seem to render a lot of the 1.10 and up blocks currently. Possibly because they aren't added to chunky yet? I'm not exactly sure how chunky is programmed and how future looking it actually it is. I'd figure it would run off of the current working minecraft version and pull the default texture pack from the minecraft installation and correspond that to the block id's. But for the life of me, I can't get Bone blocks to appear and most of my build uses them in a significant way lol.

**Comment by llbit** [comment]
This is covered by issue #376
