### ISSUE TITLE
End Rods Do Not Emit Light

### ISSUE THREAD

**Issue by Schyken** [llbit/chunky#378]
I've begun rendering an image In Chunky and this shot is only 2100/18000, but even in this early stage, it is clear to see that the End Rods are not producing light/not registered as emitters. I've resorted to using the Redstone Lamps at the side to provide light, which conveniently allows for the comparison of lighting between End Rods and Redstone Lamps, further proving the issue. Is this being worked on?
![endies-2100](https://cloud.githubusercontent.com/assets/20944747/18034680/e672f366-6cf7-11e6-8afe-15396059a074.png)

**Comment by llbit** [comment]
Pull request #373 by @electronrussia fixed this issue.
