### ISSUE TITLE
If you zoom out on a large map the map will stop rendering 

### ISSUE THREAD

**Issue by NJDaeger** [llbit/chunky#382]
I'm on a very large map and I need to zoom out very far to get to the area I need to get too, and when I zoom out very far getting ready to select my area the map rendering freezes (the chunk selection screen). But the little minimap on the top right doesn't freeze and I can move around the map around there. I am in version 1.4.0 beta1

**Comment by llbit** [comment]
Can you enable the debug console (can be enabled in the launcher under advanced settings) and post the output please?

**Comment by NJDaeger** [comment]
I will check that right now.

**Comment by NJDaeger** [comment]
This is what I got.
http://pastebin.com/Xq3Y2srW

**Comment by llbit** [comment]
Thank you, I was able to reproduce the issue. Seems like the map scale just isn't clamped to the minimum value, so it should be easy to fix.

**Comment by NJDaeger** [comment]
No problem man. Glad your working on it! Good thing it's an easy fix :D
