### ISSUE TITLE
GPU renderer support 

### ISSUE THREAD

**Issue by acterhd** [llbit/chunky#387]
Oh my god! Path Tracing now available for GPU and Java... I killed 1-2 days for port to Java from C++. 
https://github.com/acterhd/ogl-reflections
By required: lwjgl 3 version, but based on OpenGL (4.5, with some optional NV extensions, but enabled by default). 

Now question: will support of GPU rendering?

**Comment by llbit** [comment]
I don't understand, do you want Chunky to use your GPU renderer?

There is already an issue about GPU rendering support: #289

**Comment by AEnterprise** [comment]
@llbit i think he's trying to get you to use his library for GPU rendering in chunky

**Comment by acterhd** [comment]
That is just example of gpu renderer...

**Comment by acterhd** [comment]
Okay... That is not needed. Java version was broken, so permamently killed.
