### ISSUE TITLE
Cannot Run Chunky on my Win 10 PC

### ISSUE THREAD

**Issue by Kastralis** [llbit/chunky#388]
I've tried uninstalling and reinstalling chunky, but the program simply wont launch. Not sure what the issue is. I double checked my Java and JDK / JRE and it's all up to date. Trying to run 1.4.0 version's launcher

**Comment by acterhd** [comment]
For me work fine...

**Comment by llbit** [comment]
You could try the version 1.3.8 installer, and see if it works better. [This page has download links for version 1.3.8.](http://chunky.llbit.se/release/1.3.8/release_notes.html)

**Comment by Kastralis** [comment]
That's weird. I reinstalled JRE x64 Windows and it works properly now.
