### ISSUE TITLE
Add UI elements (e.g. tabs) with plugins

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#391]
I'm currently developing a distributed rendering system for Chunky and I'd like to add a new tab to upload the current scene files to the service. I thought that this would be a good thing to get started with Chunky plugins, but it doesn't seem to be possible to add new tabs with plugins at the moment.

Could you please add some API to modify the UI with plugins?

**Comment by llbit** [comment]
Support for adding render control tabs via plugins is definitely a planned feature.

**Comment by leMaik** [comment]
Is there any hacky way to add tabs right now? :smile:

**Comment by llbit** [comment]
Not really, except there is probably some reflection voodoo that could be used to add new tabs. You could perhaps replace the RenderControls class entirely via reflection.

**Comment by leMaik** [comment]
I... I think I'll just wait for the plugin API to grow. :smile:

**Comment by llbit** [comment]
I have added custom tabs now. Here is a demo project: https://github.com/llbit/Chunky-TabMod
