### ISSUE TITLE
Cannot export or save anything

### ISSUE THREAD

**Issue by Namnodorel** [llbit/chunky#392]
Every time when I try to save a scene or export something, I get this error:
(compressed, it is really not helpful that you can't copy +paste the errors pop-up windows)

Failed to save scene. [...] (The system was unable to find the specified path) java.io.FileNotFoundException:
RenderContext.getSceneFileOutputStream(RenderContext.java:111)
RenderContext.getSceneDescriptionOutputStream(RenderContext.java:88)
Scene.saveScene(Scene.java:337)

Nothing valuable in the console.

**Comment by llbit** [comment]
This probably the same issue as this one: #390 

A workaround is to go to the Chunky settings directory and manually create a subdirectory named "scenes", that should allow the scenes to be saved.

**Comment by Namnodorel** [comment]
No, I already tried that. I also can even create a file inside that folder named "myworld.json" it still says it can't find it

**Comment by llbit** [comment]
The bug should be fixed in version 1.4.1, in the meantime you could try version 1.3.8, it is available here: http://chunky.llbit.se/release/1.3.8/release_notes.html

**Comment by Namnodorel** [comment]
That works, thanks ^^
