### ISSUE TITLE
Render command line option doesn't work as expected

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#394]
I just saw that Chunky can be invoked with `-render /path/to/scene.json`, but sadly, that doesn't work and says that the scene couldn't be found. I'm pretty sure that the scene is there.

**Comment by llbit** [comment]
You are right, this should be working but I can't get it to work myself.

**Comment by leMaik** [comment]
@llbit Do you want to work on this? Otherwise I'd look into this bug so you could focus on making chunky even more awesome. :)

**Comment by llbit** [comment]
@leMaik Easy bugs like this don't need that much effort so it's usually best if I fix them myself. It is really great that you found the bug though, and that helps a lot!
