### ISSUE TITLE
Adjustable Emittance power based on source type.

### ISSUE THREAD

**Issue by NJDaeger** [llbit/chunky#395]
I would love it if we could adjust emitter power based on type. Like, lets say I want to make the glowstone really powerful, but I would like the torches to be not very powerful. I would like to set the glowstone to emittance intensity 13 and torches at 5. <- would be an awesome feature. Maybe even if we had the option to only allow certain emitters to emit light would also be nice.

**Comment by llbit** [comment]
This was added in Chunky 1.4.3. Emittance for different blocks can be adjusted in the Materials tab in the Render Controls dialog.
