### ISSUE TITLE
Adjustable lighting of HDR skymap

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#396]
At the moment, scenes with HDR skymaps are... somewhat dark (or maybe my skymaps are just bad). It would be cool if this could be fixed by applying an offset or scaling factor (or both) to the brightness of the skymap.

**Comment by llbit** [comment]
I think the "Sky light" setting in the Lighting tab should scale the skymap lighting contribution. I haven't tested it in a while though.

**Comment by leMaik** [comment]
Oh, I didn't see that option, but I looked for it in the sky tab and not in the lighting tab. Stupid me. I'll try it later. :)
Am 11.10.2016 9:45 vorm. schrieb Jesper Öqvist <notifications@github.com>:I think the "Sky light" setting in the Lighting tab should scale the skymap lighting contribution. I haven't tested it in a while though.
