### ISSUE TITLE
Running Chunky headless - refuses to do nearly anything

### ISSUE THREAD

**Issue by empirebuilder1** [llbit/chunky#402]
Attempting to run Chunky headless on my dual-core machine, going to let it run for a week or so to do a large render without tying up my main rig. 

However, I can't seem to run it or accomplish anything. Running the launcher with --update downloads chunky-core-1.4.1.jar and commons-math3-3.2.jar, placing them into the libs folder, then creating a versions folder with the 1.4.1.json inside it. Doing anything after that (passing -download-mc 1.7.10, -help, -render) results in Chunky Launcher reporting this: 
`Warning: Could not load settings from /home/user/chunky/chunky-launcher.json - defaults will be used |
No version installed |
Could not launch selected Chunky version. Try updating with --update`  

Nothing I do will make it work around this - running as root, moving the contents of the libs folder to the working directory, etc. The launcher also doesn't create a default chunky-launcher.json, which it complains about every time I try to run it. This might be the source of the problem - I'll test it in a minute.

**Comment by empirebuilder1** [comment]
Ok, so copying chunky-launcher.json and chunky.json into the chunky folder appears to let it then run normally. It appears it's not generating the config files when in CLI mode.

**Comment by llbit** [comment]
Interesting. It's supposed to generate default config files, not sure why it didn't do that. I'll try to reproduce this and see if I can see what is going wrong.
