### ISSUE TITLE
A way of saving/loading a rendering preset

### ISSUE THREAD

**Issue by NJDaeger** [llbit/chunky#407]
Can you add a way to save/load a render preset? By preset, I mean something that will save all the values you have set so you can load them up (other than the coordinates) for a render. For example, I do nighttime renders quite often, and I always render them with specific settings that need to be able to be repeated. I feel it would be nice if I could save that as a preset, open a new world in chunky, position my camera, and then load a preset and then it just puts on all the rendering values I had for the last render. It would be nice to have that implemented, either that or if it is already implemented where is it?

**Comment by llbit** [comment]
This is something that I have been wanting to add. I will try to add it in the upcoming release.

**Comment by NJDaeger** [comment]
Yay, thanks!

**Comment by llbit** [comment]
I have made some progress on a settings export/import system. It needs to be tested a bit more, but I will make a snapshot release within a few days with the export/import system:


![screenshot 2016-12-23 15 32 50](https://cloud.githubusercontent.com/assets/2757386/21456049/50b8a02a-c925-11e6-931e-eb566e4a71de.png)

**Comment by NJDaeger** [comment]
Oh wow, that looks great! Thank you so much for implementing it! :D
