### ISSUE TITLE
[question] how to change the camera position where it looks from headless mode

### ISSUE THREAD

**Issue by aycgit** [llbit/chunky#412]
see title 
formatted another way: how do you change sub things in the json with cli

**Comment by llbit** [comment]
The only real way to do this without running the GUI is to edit the scene JSON file. [This page documents the scene format.](http://chunky.llbit.se/scene_format.html)

**Comment by aycgit** [comment]
but how do you edit the xyz object of the camera object with 1 key:value

**Comment by aycgit** [comment]
same topic: do you need to reselect chunks when rendering headless and if you do, how would you input those?

**Comment by llbit** [comment]
You could edit it with a text editor. The command-line way of editing settings was not intended for making detailed edits to a scene, just as a way to easily change some simple settings like target SPP and snapshot interval etc.

You should not need to change the selected chunks when rendering a scene in headless mode. It will use the same chunks that the scene had originally.

**Comment by aycgit** [comment]
thanks, you may close this issue
