### ISSUE TITLE
Let the plugins specify their main class

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#416]
At the moment, installing plugins for non-dev users is a little more complicated than it probably should be. I like the fact the an md5 checksum is required, because this enforces at least a little security.

Specifying the main class, however, isn't straight-forward for most users (that might not even know what a class is). I'd suggest to add a manifest file inside the plugins (i.e. something like the `plugin.yml` inside Bukkit plugins). Such a file could specify the main class and more meta data that the PlugMan could display (e.g. author, version, website).

If you want, I'd love to start working on this by adding support for a plugin definition file inside the plugin.jar (I'd use JSON, as pretty much everything in Chunky is configured using JSON already) and updating PlugMan. :+1:

**Comment by llbit** [comment]
Yes, having some sort of manifest for plugins to specify their main class would be excellent! 
It would be great if you want to add this feature. I'm not working on it at the moment. Using JSON for the plugin manifest files is a good idea. I suggest using a format similar to the format used in the `.chunky/plugin` directory. If plugins have manifests, then the plugin Jars could be dropped into that folder directly.

I had planned to eventually integrate the plugin manager into the launcher. You could work on that too, if you want to.

The MD5 checksum was not indented for security purposes, only to verify that the Jar file is not corrupt. Right now the MD5 checksum is generated by the plugin manager, but I think that should also be part of the plugin manifest and provided by plugin authors.

**Comment by leMaik** [comment]
@llbit I'll start working on this asap, thank you for the feedback!

Regarding the MD5 sum: My inception knowledge tells me that it might be hard to put the md5 sum of the jar into a file into the jar whose checksum should be put into a file into the jar whose checksum should be put… :smile: Should we just drop it then?

**Comment by llbit** [comment]
> Regarding the MD5 sum: My inception knowledge tells me that it might be hard to put the md5 sum of the jar into a file into the jar whose checksum should be put into a file into the jar whose checksum should be put… :smile: Should we just drop it then?

Haha, you are right! I didn't think that through completely. Jar files have an check sum built-in via the Zip format anyway, so it is probably redundant to use extra MD5 sums. Let's forget about checksums for the moment, it's always possible to add that later.

**Comment by leMaik** [comment]
Allright, I'll skip the checksums then. :+1: 

I started yesterday and added a plugin class to track the plugin information. It would be possible to let plugins extend that (abstract) plugin class instead of implementing the interface. Would you like to keep the interface or would it be okay to let them extend an abstract class instead? For now, I sticked with the interface and added the plugin class beside it (the plugin class has a method that calls through to the interface's `attach` method). I wasn't really sure how you'd want it to be. :wink:

**Comment by llbit** [comment]
I'm not sure I understand the need for an abstract class. I think it would be better to add getter methods to the plugin interface. For example:

```java
interface Plugin {
  String getName();
  ...
}
```

**Comment by leMaik** [comment]
My current plan is to read the plugin name, version and author from the manifest, so the author doesn't need to write getters but just needs to put the information into the manifest. This allows reading these values without _executing_ the jar, which might become handy for the plugin manager or an (online?) plugin gallery.

I'll start pushing in my fork soon, so that we can talk about actual code. :+1:

**Comment by leMaik** [comment]
@llbit Plugin loading works so far. :tada: 
I decided to keep the plugin interface and just wrap it into a `ChunkyPlugin` class that contains the implementation class and the meta information read from the `plugin.json` file.
More code coming soon [in my fork](https://github.com/leMaik/chunky/tree/better-plugins). I'll submit a PR later…

**Comment by llbit** [comment]
@leMaik I took a brief look at your code. I saw some things that I would like to do differently, but maybe it's better if you create a PR with your finished code and then I can suggest changes.

> I'll include this. 🎉

Great! That would be very good to have.

Sorry for the reply lag btw, I haven't had much time for Chunky lately.

**Comment by leMaik** [comment]
@llbit I'm interested in your feedback during the development, especially if there are any conceptual converns. Refactoring the future PR is easy, but changing the plugin architecture would be a little frustrating then. So feel free to comment on my commits. :+1:

Didn't manage to continue this weekend, but I'll try to continue next weekend.

**Comment by llbit** [comment]
@leMaik I gave you some feedback on the commits. I like the idea of having an extra helper class (`ChunkyPlugin`) to launch plugins, but it does not need to store any data. It would also be much simpler if you just use the parsed `JsonObject` directly to access the plugin information in `ChunkyPlugin.load`.

**Comment by leMaik** [comment]
@llbit Thanks a lot, I replied them. :+1: 
I'd like the idea of `ChunkyPlugin` being _the_ abstract plugin class (replacing the `Plugin` interface) instead of a helper class more, though.

**Comment by llbit** [comment]
@leMaik I don't know if you have been seriously code reviewed before, but don't take my comments personally. I'm not attacking your coding style, just trying to teach you my own coding style.

I know from experience that code review comments can feel nitpicky and wrong, but I have learned a lot from receiving reviewer comments.

**Comment by leMaik** [comment]
@llbit You comments are _supposed_ to be nitpicky. It's fine! :wink:
What I don't like (and what really de-motivates me here) is that the comments don't discuss important bits but ended up being a discussion on object-oriented programming vs. using string maps. :disappointed:

I'll continue my implementation and I'd be happy to receive further feedback from you and I'll improve it then. :+1:

**Comment by llbit** [comment]
I like discussing OOP and different styles of programming because I like to experiment with different paradigms and always try be critical of, and re-evaluate, the paradigms that I use.

**Comment by leMaik** [comment]
@llbit I finally found time to work on the plugins again. I just started to merge the plugin manager into chunky and thought about the compatibility warning mentioned above.
What do you think about using semantic versioning? That way, a plugin could specify that it is compatible with e.g. `~1.4.0` and then we'll only throw a warning if you try to use it with another minor or major version. There already are some semver libraries for Java out there, too.

**Comment by llbit** [comment]
@leMaik I want to start with a conservative system warning if the version does not match exactly. The plugin API is likely to change with each minor release now, but in the future it will become more stable.

**Comment by llbit** [comment]
@leMaik how's it going with your pull request? If you don't have time to work more on this it would be great if you create a pull request with the work you have done and I can complete it when merging. It's up to you, but I think it would be a shame if your work does not get merged now that you spent some time on it.

**Comment by leMaik** [comment]
@llbit Well, I didn't really have time to work on it since march (when the summer semester started). :disappointed: I'll have some more time to work on the plugin _manager_ in the coming months (august ~ october), hopefully.

I'll create a PR with what I already have soon. I added a manifest that lets plugins specify their main class and other metadata, which resolves this issue. :+1:

**Comment by llbit** [comment]
@leMaik awesome, thanks!

**Comment by leMaik** [comment]
@llbit The plugin manager is a great new feature, thanks! :+1:
