### ISSUE TITLE
Stereographic projection does not apply depth of field

### ISSUE THREAD

**Issue by cedeel** [llbit/chunky#425]
The stereographic projection mode does not apply depth of field based on selected settings.

1. Select the Camera tab
2. Select Stereographic from the Projection mode drop down
3. Modify the Depth of field slider

After following these steps, no depth of field is applied to the rendered image.

**Comment by llbit** [comment]
As far as I know, depth of field is not well-defined for stereographic projections.

Depth of field is normally simulated by perturbating the ray origin in the image plane, however stereographic projections have a single point of origin - there is no perpendicular plane perturbate the ray origin in. Perturbating the ray origin in a circle would cause blurring, but there would be no point of convergence so it would just blur the whole image.

Feel free to give a suggestion for how this can be solved. I don't think it can be solved, so I'm closing this.

**Comment by cedeel** [comment]
In that case, would it be possible to disable the controls in the GUI as it can possibly lead to confusion when they have no effect?
