### ISSUE TITLE
Entity render does not work in headless mode

### ISSUE THREAD

**Issue by AR1ES** [llbit/chunky#428]
Headless rendering rewrites scene.json and removes actors array from it.

**Comment by llbit** [comment]
Which Chunky version are you using?

**Comment by AR1ES** [comment]
Version 1.4.2.
Scene.json remains unchanged when I run headles mode after rendreing scene in GUI. As far as I understand, this is because the scene has already been rendered.
Therefore, you must delete the dump file or change some property in the Scene.json (width, height, etc.) and then run headless rendering to reproduce this error.

**Comment by llbit** [comment]
I think this has been fixed in the current snapshot. I can not reproduce the error.
