### ISSUE TITLE
[a3] Y-Cutoff & Signs (and a suggestion)

### ISSUE THREAD

**Issue by chland** [llbit/chunky#439]
There is a funny bug regarding the Y-Cutoff and signs.

Lets say you've got a bunch of signs at Y=40 and you set Y-Cutoff to 60, the signs will get rendered in the "void":

![cutoff](https://user-images.githubusercontent.com/472894/27955728-7a4cd06a-6316-11e7-8cac-ab8e5562e5d9.jpg)

Btw. would it be possible to change the whole cutoff-function to not only change the lower Y-limit but the upper Y-limit, too? This could be useful for the Nether (to get rid of the ceiling) or when people only want to render an area between for example Y=20 and Y=45.

**Comment by llbit** [comment]
That's interesting. I never considered that some block-like entities will avoid the Y cutoff value.

Sure, an upper bound could be added to the Y cutoff. I think someone might have requested that before, but it was not a high priority at the time and was forgotten.

**Comment by chland** [comment]
So far I've only seen this happening with signs. Hoppers, Droppers, Rails, Levers, etc. all disappear if the cutoff is changed. If I find anything else i'll let you know :)

**Comment by llbit** [comment]
Most of those blocks you mentioned are rendered as part of the voxel octree, so they get removed by the Y cutoff.

**Comment by chland** [comment]
I noticed a little "bug" with paintings and the Y-Cutoff. When the Y-Cutoff happens "inside" the painting, it will extend into the "void":

![paint_bug](https://user-images.githubusercontent.com/472894/28872296-e0f0cc14-7788-11e7-945f-79e777cc0594.jpg)

But this is such a strange edge-case that I don't know if its worth fixing :)

**Comment by llbit** [comment]
@chland  If it doesn't cause any real problems I will leave it like that because it would be sort of tricky to fix.

**Comment by chland** [comment]
Personally, I don't really care :) And I doubt that it will cause any real issues as people can just remove the paintings or raise/lower the Cutoff by a block.
