### ISSUE TITLE
Beds in Pre-1.12 worlds

### ISSUE THREAD

**Issue by chland** [llbit/chunky#443]
I know, that there is already a report on the new beds (https://github.com/llbit/chunky/issues/433) but there is a problem with old worlds regarding beds, too. First of all, Chunky now displays this error-message in the debug-window:

`Loading 464 textures from [...]\.minecraft\versions\1.12\1.12.jar
Failed to load textures:
	bed_feet_side
	bed_feet_end
	bed_head_side
	bed_feet_top
	bed_head_end
	bed_head_top`

which makes sense, I guess (as the textures were moved to assets/minecraft/textures/entity/bed). But beds in old worlds now render like this:

![bed_bug](https://user-images.githubusercontent.com/472894/28338523-83bdd0e4-6c09-11e7-890d-b0a390e4377f.png)

I guess the best way to deal with them would be to add support for colored beds and replace all old beds upon loading with the new red bed.

**Comment by llbit** [comment]
The problem is that the old bed textures were removed in Minecraft 1.12. If you use a pre-1.12 texture pack it should work, as they include the old bed textures.

**Comment by chland** [comment]
Yeah, I tested it and the workaround works. I created a simple Resource Pack that only contains the bed-textures, added it to Chunky and that fixed the visual bug with old beds. 

But I think it might be better if it would somehow work "out of the box" by either generating the missing textures "on the fly" from the new "[...]/assets/minecraft/textures/entity/bed/red.png" file or replacing the old beds with new entities if you add the colored beds to chunky.

**Comment by llbit** [comment]
Bed rendering has been improved for Minecraft 1.12. See commit ec0773f0b922eb73e20d81bd31095184ab1cf274. Missing now is a texture loader adapter to convert old style bed textures to the new entity texture format so that pre-1.12 texture packs work with the new rendering.
