### ISSUE TITLE
Add tabs to the main window with plugins

### ISSUE THREAD

**Issue by leMaik** [llbit/chunky#447]
It would be nice if it was possible to add new tabs to the main window (the bottom right tab panel). This could be done with a new transformer, similar to how render control tabs can be added.

**Comment by llbit** [comment]
This is a good idea. I'll add it!

**Comment by llbit** [comment]
I've added API calls to add a main window tab transformer now. The [tabmod plugin](https://github.com/llbit/chunky-tabmod) has been updated to demonstrate this:

![screenshot 2017-08-02 23 32 02](https://user-images.githubusercontent.com/2757386/28896036-1dea21fe-77db-11e7-8f83-7bee78893e60.png)

**Comment by leMaik** [comment]
Nice, thank you! :+1: Is there a way to add a custom icon to the tabs?

**Comment by llbit** [comment]
@leMaik yes, just use [Tab.setGraphic()](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Tab.html#setGraphic-javafx.scene.Node-).

**Comment by leMaik** [comment]
@llbit Is there any way you could automatically publish snapshot builds whenever the code changes and compiles? That would make playing around with the new features a little simpler. :wink:

**Comment by llbit** [comment]
I have a bot that periodically checks for new commit and uploads a snapshot. Should be up within a few hours at least from last commit.

**Comment by llbit** [comment]
The snapshot name is always latestrelease-SNAPSHOT

**Comment by llbit** [comment]
This is the Maven snapshots. The alpha/beta builds are manual

**Comment by leMaik** [comment]
Okay, thank you for the clarification.
