### ISSUE TITLE
[1.4.4-a2] Something (probably) odd about Glass-Blocks

### ISSUE THREAD

**Issue by chland** [llbit/chunky#450]
Yesterday, I created a new test-scene to test the banner-feature a little bit more. While doing so I decided to add more stuff to the scene to test some other things and stumbled across something "odd". I placed a bunch of yellow and blue glass blocks. The result is this:

![glass](https://user-images.githubusercontent.com/472894/28974603-340ca896-7937-11e7-8574-d6d8916c6ce7.jpg)

The left row consists of multiple blocks with a 1 block gap between them. The ones on the right don't have air-gaps. IMHO the glass on the right renders incorrectly. the blue glass-blocks should be visible similar to what it looks like on the left but it renders if they weren't there at all.

Is this a "feature" or a "bug" ?

**Comment by leMaik** [comment]
This is how it looks ingame:
![2017-08-05_19 15 42](https://user-images.githubusercontent.com/5544859/28997359-867b4e26-7a12-11e7-8cfb-7ebe656b95c1.png)

Only equal-color glass blocks should "connect".

**Comment by leMaik** [comment]
This will be fixed in the next Chunky snapshot.

![glass-541](https://user-images.githubusercontent.com/5544859/78611804-0db32e80-7868-11ea-8ae2-c2e488df80d2.png)
