### ISSUE TITLE
[bug] Select world window stuck on "Loading worlds list"

### ISSUE THREAD

**Issue by Scrillrock** [llbit/chunky#456]
Firstly, when I open Chunky from the launcher, it stays in world "unknown" and everything in the preview area stays white with black diagonals. From what I've read, I think it should ask me to choose a world itself.
![capture](https://user-images.githubusercontent.com/31572524/29997532-6fa19eb8-901e-11e7-9584-3715421bdd9a.PNG)
Then, when I try selecting a world after all, this shows up:
![capture2](https://user-images.githubusercontent.com/31572524/29997545-aec606ec-901e-11e7-928a-047d1046c086.PNG)
And it never changes.

I have no idea what to do.

**Comment by llbit** [comment]
This might happen if the world selector can't find your Minecraft installation. If you look in the Chunky Launcher, does the Minecraft folder path point to the right directory?

**Comment by Scrillrock** [comment]
It does point to the right folder. And about this referenced issue, how do I implement this code?

**Comment by llbit** [comment]
The code change is not released yet, but I will upload a new snapshot version later today, you can try [downloading the snapshot](http://chunky.llbit.se/snapshot.html) and see if it works better then. I'll post a comment when the snapshot is available.

**Comment by Scrillrock** [comment]
Thank you very much! This will really fix the thing, I'm all ok with selecting the world manually. But can you tell why does this occur in the first place?

**Comment by llbit** [comment]
I'm not sure why it hangs on loading the world list, but it might be caused by some error that crashes the thread that tries to load the world list. That would prevent it from re-enabling the buttons in the interface.

Do you have many Minecraft worlds?

**Comment by Scrillrock** [comment]
15-20 worlds. Maybe it's got a limit in showing rows with worlds to choose from?

**Comment by Scrillrock** [comment]
Oh, the snapshot is working perfectly, thousands of thanks! One more thing, if you mind, how do I make a scene, where light is emitted from the player, or just is there without an emitter in the area? I'm making a map with no physical light sources, the player is given night vision, and I wanted to try and showcase the inside of one of the levels.

**Comment by llbit** [comment]
Oh, that's difficult. There is no good solution for that right now I think. You can try generating ambient light by changing the material properties for specific blocks like grass/stone. Try adding some emittance to the stone blocks inside a cave for example.

![screenshot 2017-09-03 23 02 58](https://user-images.githubusercontent.com/2757386/30006597-10ae85fe-90fc-11e7-99c0-471618de4cc3.png)
