### ISSUE TITLE
Hue shift for Foliage

### ISSUE THREAD

**Issue by Consue** [llbit/chunky#458]
One of the things that always troubled me about chunky is that the hue of taiga leaves are different from those found in minecraft. Im minecraft the hue of taiga leaves is normally a coldish green while in chunky it takes the color of the foliage color map, which with a desert biome turns out to be an odd shade of green. If it were possible to shift the hue to more closely resemble the colors inside of mc that would be amazing. Im a proud and frequent user of chunky as seen [here ](https://twitter.com/Consue_IdeaGen)

**Comment by llbit** [comment]
Interesting, I always thought that spruce and birch trees were affected by the foliage color map, but now I did some testing and it seems like those two trees are not affected by biome for their foliage color. It should be an easy change to make them work more like in Minecraft.

Thanks for posting this issue! The renders on your twitter are amazing by the way!

**Comment by llbit** [comment]
Okay, that was simple enough to fix, but the current colors may need to be tweaked to be more like the hard-coded color values in Minecraft. I just took a couple screenshots for reference.

**Comment by llbit** [comment]
I'll upload a new snapshot in a moment with these changes so you can test it.
