### ISSUE TITLE
cant set memory limit higher than 1,020

### ISSUE THREAD

**Issue by brando123542** [llbit/chunky#459]
I want to set the memory limit all the way up to 16,000 but cannot. Every time I try, it comes up with a Java error.

**Comment by Lergin** [comment]
I just had the same error and got it to work by using the 64-bit java version instead of the 32-bit

**Comment by llbit** [comment]
This issue pops up occasionally, so I added some info about it on [the troubleshooting page](http://chunky.llbit.se/troubleshooting.html).

Closing this now because I guess this was resolved already.
