### ISSUE TITLE
Coords Limit

### ISSUE THREAD

**Issue by istoOi** [llbit/chunky#460]
Tryed to render a build at x130,000 z130,000 but the preview is empty and "stuck" at 0,0 coords. I can preview the nether at x16,000 z16,000 tho.

**Comment by llbit** [comment]
This needs more investigation to find where the error is. I will try to reproduce the issue when I have time.

**Comment by jackjt8** [comment]
Not reproducible/Fixed.

1.4.5 @ 130,000, 130,000

![image](https://user-images.githubusercontent.com/3740917/80319447-2334cc00-8808-11ea-9e95-aba1b1090bee.png)

2.1.0-282 @ 130,000, 130,000
![image](https://user-images.githubusercontent.com/3740917/80319567-ecab8100-8808-11ea-8876-663102d5a6c5.png)

Can also load chunks at ~30,000,000 blocks out without any issue.

**Comment by leMaik** [comment]
Thanks @jackjt8 for trying to reproduce this. I'll close this since it's been 2.5 years. If anyone gets the same problem, please open a new issue.
