### ISSUE TITLE
No shadows in 3D scene rendering.

### ISSUE THREAD

**Issue by Dushess** [llbit/chunky#461]
Hello, i use latest version (1.4.3) and have little trouble. Shadows no more rendering. Probably related to map version, also it have modded stuff. Just 2 screens, 1st - 1.10.2, 2nd - 1.11.2. Modded things, displayed as border blocks is Chisels&Bits and LittleTiles.
[1.10.2](https://i.imgur.com/owAkQGf.jpg)
[1.11.2](https://i.imgur.com/tHMuFvr.png)

No, 1st picture is 1.11.2 too, but done about month ago.
May be related to Java version, but i not sure...

Also [map dump](https://www.dropbox.com/s/7wqhlt15jy0jqu8/SA-2%20Samson%20%281.11.2%20using%20C%26B%2BLT%29.dump?dl=0)

**Comment by Dushess** [comment]
Probably created in laptop, don't remember, will check later.

**Comment by llbit** [comment]
Did you start the render? The second image looks like just the preview image.

**Comment by Dushess** [comment]
Uhh, really, ok, one moment.

**Comment by Dushess** [comment]
Uhm, also one small suggestion, make shadow less intensive. Maybe slider for configure it, just because i can barely see things under so powerful shadows. Control it by sun brightness makes everything too bright, but shadows still looks not good.
