### ISSUE TITLE
Regarding support for Minecraft 1.13 (and 1.14)

### ISSUE THREAD

**Issue by chland** [llbit/chunky#463]
This is just a very general (and most likely incomplete) list of things that will change with 1.13/1.14 that might (or might not) break Chunky:

1.13 basically removes the block-ID limit and brings a LOT of changes to the game:

* Trapdoors, Buttons and Pressure Plates now exist for all wood-types (15 (?) new "blocks")
* Pumpkins now come in 2 versions: with a carved face and without
* some blocks that were only obtainable in Creative are now obtainable in game: bark blocks for all wood-types, smooth quartz/sandstone/stone-blocks, mushroom-blocks (shouldn't be much of an issue in Chunky as they were already supported)
* Resource-Packs were completely re-organized - tons of changes to filenames and folder-structure (you can check out https://www.reddit.com/r/Minecraft/comments/7f5712/python_scripts_to_rename_your_resourcepack_to/ and http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/2874303-resourcepackporter-a-tool-to-port-1-12-resource to see some of the changes)
* block-metadata was removed from the game and moved to block-states (no more "abused" damage-values like for wool or stone-variants) -> https://minecraft.gamepedia.com/1.13/Flattening

I couldn't find any details on the changes they made to the save-files :-/

And 1.14 will be as "bad" as 1.13 - while so far nothing is known about any further fundamental changes to save-files, block-states, etc. it WILL add new biomes, new blocks and modify the way liquids work.

* if you surround a water-source with fences, the water will spread as if there aren't any fences at all and it will be rendered around the fences -> check out: http://www.minecraftforum.net/forums/minecraft-java-edition/recent-updates-and-snapshots/2872402-update-aquatic-1-14-all-information-we-have-so-far
* same seems to be true for grass or flowers 
* currently mostly just a rumor but 1.14 might also add a ton of new slabs and stairs for existing blocks (stone, granite, andesite, etc.)

**Comment by llbit** [comment]
The resource pack renaming stuff is pointless. I wish Mojang wouldn't do that. It only creates extra work for modders.

The NBT format has a new tag type: TAG_Long_Array (12).

The new level format looks interesting. I'm not sure how it works yet. Chunk sections now contain an opaque long array and a block type palette. Here is the new section layout:

```
TAG_Compound
  BlockStates:
    TAG_Long_Array: 256
  Palette:
    TAG_List
      TAG_Compound
        Name:
          TAG_String: "minecraft:air"
      TAG_Compound
        Name:
          TAG_String: "minecraft:bedrock"
      TAG_Compound
        Name:
          TAG_String: "minecraft:granite"
      TAG_Compound
        Name:
          TAG_String: "minecraft:stone"
      TAG_Compound
        Name:
          TAG_String: "minecraft:iron_ore"
      TAG_Compound
        Name:
          TAG_String: "minecraft:andesite"
      TAG_Compound
        Name:
          TAG_String: "minecraft:coal_ore"
      TAG_Compound
        Properties:
          TAG_Compound
            lit:
              TAG_String: "false"
        Name:
          TAG_String: "minecraft:redstone_ore"
      TAG_Compound
        Name:
          TAG_String: "minecraft:diorite"
      TAG_Compound
        Name:
          TAG_String: "minecraft:gravel"
      TAG_Compound
        Name:
          TAG_String: "minecraft:diamond_ore"
      TAG_Compound
        Name:
          TAG_String: "minecraft:dirt"
  SkyLight:
    TAG_Byte_Array: 2048
  Y:
    TAG_Byte: 0
  BlockLight:
    TAG_Byte_Array: 2048
```

Eight bytes of block data per block seems ludicrously high if it's just indexing the palette. At most one byte would be needed in that case. There must be some other data packed into the block state array.

**Comment by llbit** [comment]
There might be some extra compression of the block data in this new level format. If I just unpack the `TAG_Long_Array` data to bytes and treat it as indices into the palette, it gives this result:

![screenshot 2018-01-21 20 49 07](https://user-images.githubusercontent.com/2757386/35198302-ea6a2452-feec-11e7-8487-8abb327c3fb6.png)

**Comment by llbit** [comment]
I figured out the new block data format. The sections now contain long arrays which are just bit packed arrays of palette indices. The bit width for the bit packing is determined by the number of elements in the palette, with a minimum of 4 bits. If there are more than 16 elements in the palette then the bit width is `ceil(log2(paletteSize))`.

I have a basic working implementation of a parser for the new format, but it does not handle all possible palette entries yet. It will take some more work to decode the palette to Chunky's own block data format.

**Comment by chland** [comment]
Btw. are you going to support both the old and new format or are you going to switch to 1.13+ entirely?

**Comment by llbit** [comment]
@chland My goal is to support the old and new (flattened) Anvil formats.

**Comment by techkid6** [comment]
Is this still ongoing or has the issue just not been closed yet?

**Comment by chland** [comment]
So far, Chunky doesn't support 1.13 worlds (AFAIK you will only see ocean in the main screen when you try to load worlds containing 1.13 stuff).

AFAIK, llbit has been busy lately with IRL stuff and it will most likely still take some time until 1.13 worlds can be rendered.

**Comment by techkid6** [comment]
Gotcha.  Just checking to see that the thread was still around, thanks!

**Comment by alvarocastro** [comment]
Came here for this same reason. Too bad I started an enormous project (in 1.13) that wanted to render in an isometric view just to findout this version isn't supported :(

**Comment by chland** [comment]
IDK how far you got with analyzing the new chunk-format, @llbit but in case you need additional infos, this might help:

https://www.minecraftforum.net/forums/minecraft-java-edition/recent-updates-and-snapshots/2894808-minecraft-1-13-new-chunk-format-fully-decoded-read

**Comment by timakro** [comment]
Looking forward to this as well!

**Comment by HorlbogeDE** [comment]
Are there any news on this topic? I cant wait to render 1.13 worlds!

**Comment by alvarocastro** [comment]
Read on reddit, can't remember which thread, that the update is paused because he is making a tesis.
So the best we can do is:
A) Colaborate in the project or
B) Just be patient and wish him luck!

**Comment by llbit** [comment]
@HorlbogeDE @alvarocastro I'm working on support for 1.13 right now.

Just parsing the new world format is the easy part and is already working. The problem is that the current way Chunky represents blocks with numeric IDs does not support the new block palettes that Minecraft uses.

There is a lot that needs to be done to adapt Chunky to cleanly support the new way blocks are represented so it will take a lot of work to complete this redesign for 1.13.

**Comment by llbit** [comment]
I created a new issue with a more detailed checklist for 1.13 support: #518

**Comment by llbit** [comment]
Experimental 1.13 support is available in new Chunky 2.0 snapshots. You can try the snapshots, but be aware that there may be bugs that can damage existing scenes!

To try the 2.0 snapshots follow these steps:

* Download the latest Chunky Launcher (v1.11.1 or later) from https://chunkyupdate2.llbit.se/ChunkyLauncher.jar
* Open the launcher and under the "Advanced" tab set "Update Site" to `http://chunkyupdate2.llbit.se`
* Enable snapshot versions in the Chunky launcher.
* Check for update and install 2.0-alpha5 or later.

**Comment by alvarocastro** [comment]
I was getting an error with the "Update Site", it should be "http://chunkyupdate2.llbit.se/" (with a slash in the end)

**Comment by llbit** [comment]
@alvarocastro thanks, that was an oversight. I edited the comment. I'll make the updater handle the slash better for future versions.

**Comment by caiosm1005** [comment]
No public repository for Chunky 2? I got an IndexOutOfBoundsException error after loading a previously saved scene that I would love to try to tackle and push a PR for,

**Comment by leMaik** [comment]
@caiosm1005 I had to search a while to find it, so I thought I'd reply even if it's been a week. Chunky 2 is in the `flattening` branch, [over here](https://github.com/llbit/chunky/tree/flattening).
