### ISSUE TITLE
Shadow intensity

### ISSUE THREAD

**Issue by Dushess** [llbit/chunky#466]
Small suggestion, make shadow little less intensive. -15% or maybe slider for configuring it, just because not so easy to see things under current shadows. Control it by sun brightness makes everything too bright, unwanted way.

**Comment by llbit** [comment]
Hi, thanks for the suggestion. Unfortunately, it is not currently possible to do what you ask about.

Chunky renders without ambient light, which is commonly used in rasterizing renderers to simulate global illumination. The lack of ambient light means that the shadows are entirely an effect of light propagation from the sky/sun/torches in the scene. Hopefully this explains why there is no way to change the relative darkness of shadows other than tweaking sky light/sun light/emitter intensity.

**Comment by Dushess** [comment]
Hmm, what if i'll put some ligh sources behind the camera?

**Comment by llbit** [comment]
That could work. Another alternative is to enable emitters, then change the emittance for all blocks to 0.01 in the Materials tab. That will make all blocks lit. It will look weird, but maybe not too weird. If the sun and sky light intensities are increased, and exposure is reduced, then it will look less weird but you'll get a kind of ambient light effect.

![screenshot 2018-01-24 07 33 04](https://user-images.githubusercontent.com/2757386/35317890-377e4ca8-00d9-11e8-9f0a-aff5948b6a69.png)
![screenshot 2018-01-24 07 33 40](https://user-images.githubusercontent.com/2757386/35317891-3925c09a-00d9-11e8-84cb-281d006dcba3.png)
![screenshot 2018-01-24 07 33 51](https://user-images.githubusercontent.com/2757386/35317898-3e3f157c-00d9-11e8-98ac-0d6582ba72f5.png)

**Comment by Dushess** [comment]
Huh, actually enough tweak Sky Light a bit, with Sun Intensity it makes solution.

**Comment by Dushess** [comment]
![sa-2 building - 12 02 18 - ed - scr](https://user-images.githubusercontent.com/15954961/36120944-dcfde662-1055-11e8-95f1-0369a052247e.png)
Cabin door area, how it looks?
