### ISSUE TITLE
Dark oak tree-leaves are the wrong color. They should be dark green, but are instead blue like spruce trees.

### ISSUE THREAD

**Issue by grandfatherclock** [llbit/chunky#467]
Screenshot: https://i.redd.it/4th9jc07ced01.png

In-game screenshot for comparison https://imgur.com/a/MRfGk

**Comment by llbit** [comment]
Thanks for the bug report. I'll look into it.

**Comment by chland** [comment]
Just to let you know: i did a quick test in some different biomes (to make sure its not something caused by the biome-colors). Dark Oak leaves are always broken (in Swamps, deserts, Plains, etc.) and everything else renders as expected.
