### ISSUE TITLE
Crops and grass block sides having missing textures.

### ISSUE THREAD

**Issue by Hex621** [llbit/chunky#470]
I installed chunky and for some odd reason all crops have missing textures. and if i doesn't use a resource pack the side of every grass block is missing as well.

What could be the problem?
![rp3 3-90](https://user-images.githubusercontent.com/36451691/36162706-73ce3dee-10e7-11e8-932f-a0e60569bbe6.png)

![final-331](https://user-images.githubusercontent.com/36451691/36162271-39c7938a-10e6-11e8-9bf5-8ae0eedf881a.png)

**Comment by llbit** [comment]
This is a texture pack loading problem. If you use the latest Minecraft snapshots, they have renamed a lot of textures so that Chunky can't load the right textures. A solution is to manually add an old Minecraft Jar as a texture pack.
