### ISSUE TITLE
Sky Light broken?

### ISSUE THREAD

**Issue by craqgerbil** [llbit/chunky#472]
I may be doing something wrong here, but in the latest, I can't seem to get the sky light to work. I would like a general low light level underground.  I can't remember if it would do this in the past.

**Comment by Dushess** [comment]
You can try to tweak Sky Light combined with Sun Intensity.

**Comment by llbit** [comment]
A similar question was asked already in #466 
Sky light works as it should - if there is no path from the sky to your caves, they will be completely dark.
Try enabling emitters if you have torches or lava in the cave.
