### ISSUE TITLE
What happen about this?

### ISSUE THREAD

**Issue by Edmunlee** [llbit/chunky#485]
![image](https://user-images.githubusercontent.com/41871319/43368130-d6b82444-938a-11e8-8ba4-e0325ee813c2.png)
my main base just shown blue , but another place its fine

**Comment by Dushess** [comment]
Please describe more, no idea, what wrong as you said. Maybe small preview not match large one...

**Comment by Edmunlee** [comment]
My problem with this is that my main area is completely blue and all areas I already went since 1.13. turn blue aswell. So I can't see the details and borders of the coast and stuff like that. Any solutions?﻿

**Comment by NJDaeger** [comment]
Wait until chinky is updated to 1.13

**Comment by leMaik** [comment]
The waiting is over :tada:
