### ISSUE TITLE
[Feature] Force Chunky to use resources from a particular Minecraft-Version!?

### ISSUE THREAD

**Issue by chland** [llbit/chunky#486]
I don't know if i'm missing something but Chunky seems to always use the latest (stable?) release of minecraft when it looks for the default resource pack to use?

Wouldn't it be better to allow the user to select the version chunky uses?

For example there could be an additional select-box in the "Edit Resource Packs" dialog where the user could select the "base"-pack/version chunky uses.

**Comment by llbit** [comment]
Yes, this is an excellent suggestion and something I've been wanting myself.

**Comment by leMaik** [comment]
See #202
