### ISSUE TITLE
[Feature] Preview-Window moving upon "Reload Chunks" / "Load selected chunks"

### ISSUE THREAD

**Issue by chland** [llbit/chunky#488]
Just a very, very minor feature-request.

The "Render Preview" Window always re-aligns itself to the right of the "Render Controls" window when you (re)load chunks. IMHO it would be better if the Preview-Window would stay at its position. I'm often using chunky in a way where the Render Controls are on one monitor and the Preview on another and its kinda annoying when i have to move the Preview-window around every time i (re)load chunks.

**Comment by leMaik** [comment]
I guess this is fixed with the single-window ui.
