### ISSUE TITLE
[Feature] Coordinates in the main window

### ISSUE THREAD

**Issue by chland** [llbit/chunky#489]
Another very, very minor feature-request.

It would be nice if the main window would display the "block-coordinates" in addition to the chunk-coordinates. Right now the pop-up displays something like:

> Chunk: [10, -3] plains

it would be nice if you could add the block-coordinates, too. Something like:

> Chunk: [10, -3] plains
> Coords: 163, -51

**Comment by ThebesAndSound** [comment]
I was just about to suggest this, its hard to do x8 conversions in my head

**Comment by llbit** [comment]
This is a simple issue but I don't have time for it right now. Any new coder who wants to help could probably add this easily.
