### ISSUE TITLE
Snap package for Linux

### ISSUE THREAD

**Issue by NatoBoram** [llbit/chunky#494]
Linux has a new way to easily pack applications and distribute them. Snaps offer many, many advantages over downloading random packages from random websites. I think it would be better for all Linux users if Chunky was distributed as a snap.

There's an official guide to help building Java snaps : https://docs.snapcraft.io/build-snaps/java

**Comment by llbit** [comment]
This would be great for making sure that Chunky runs with a compatible JVM on Linux. I don't have time to set up a build process for this currently, but I would like to support snaps on Linux in the future.
