### ISSUE TITLE
Lava not emitting properly

### ISSUE THREAD

**Issue by Paril** [llbit/chunky#498]
https://i.imgur.com/PnctJ6J.png

High intensity to show the lava is lighting the inner snow bits but not the tops as it should/did before. This is with latest snapshot.

EDIT: Okay, so this might be because of the snow layers. They aren't transparent or anything so it seems it is blocking the emitting from working. Anything that can be done about that? Transparency can't be controlled via Materials it seems..

**Comment by llbit** [comment]
This is actually working as intended. The light from the lava is not hitting the top of the snow because there is no line of sight from the top of the lava to the top of the snow, and the light can not bounce off a ceiling above the snow.
