### ISSUE TITLE
Saving render with transparent sky enabled is very slow

### ISSUE THREAD

**Issue by The7thOne** [llbit/chunky#501]
I don't know if it is supposed to be this slow, but saving renders with a transparent sky/background takes an unreasonable amount of time, sometimes upwards of 5-10 minutes depending on chunk selection size. This occurs with both render dumps and saving the current frame. For additional context, I'm saving them to PNG.
Edit: I'm using the 1.4.6 snapshot, but this has occurred on older versions as well.

**Comment by leMaik** [comment]
This will be fixed by implementing #335, which is done in the next snapshot.
