### ISSUE TITLE
Red X's Issue... but the directory is correct. 

### ISSUE THREAD

**Issue by Crusher6581** [llbit/chunky#503]
When I try to render a world, a black box with a red x inside of it appears, i've read the troubleshooting guide but the selected directory is the correct and only .minecraft directory I have, still has the missing textures.

**Comment by Vlad0Crystal** [comment]
> Когда я пытаюсь визуализировать мир, появляется черный ящик с красным крестиком внутри, я прочитал руководство по устранению неполадок, но выбранный каталог является правильным, и единственный каталог .minecraft, который у меня есть, все еще содержит пропущенные текстуры.

I can record a video, it happens on 1.13.2

**Comment by Vlad0Crystal** [comment]
> Когда я пытаюсь визуализировать мир, появляется черный ящик с красным крестиком внутри, я прочитал руководство по устранению неполадок, но выбранный каталог является правильным, и единственный каталог .minecraft, который у меня есть, все еще содержит пропущенные текстуры.

**Comment by Vlad0Crystal** [comment]
> When I try to render a world, a black box with a red x inside of it appears, i've read the troubleshooting guide but the selected directory is the correct and only .minecraft directory I have, still has the missing textures.


I can record a video, it happens on 1.13.2

**Comment by chland** [comment]
> > When I try to render a world, a black box with a red x inside of it appears, i've read the troubleshooting guide but the selected directory is the correct and only .minecraft directory I have, still has the missing textures.

There seems to be some kind of bug on machines with Minecraft 1.13+ installed where Chunky tries to load the 1.13 resource pack when you try to render a 1.12 world. In those cases you can see the blocks in the scene but they are (all) black with red crosses on them. In this case you can try to load a 1.12 resource-pack or remove 1.13 completely. But i'm not 100% sure under what circumstances this bug happens.
 
> I can record a video, it happens on 1.13.2

Chunky doesn't yet support 1.13.2 worlds. So if you try to load them you will end up with a lot of strange bugs and pretty much nothing will work.

**Comment by jmichaelbarker** [comment]
I can confirm that this issue is accurate; if 1.13.x is installed, Chunky will attempt to load 1.13.2 resource packs. Once it is removed (from minecraft/versions/1.13.2 for instance), Chunky picks up the correct resources.
