### ISSUE TITLE
Documentation typoS? (Website)

### ISSUE THREAD

**Issue by monotonehell** [llbit/chunky#504]
1. According to http://chunky.llbit.se/minecraft_compatibility.html 

> Minecraft Compatibility
> Chunky can render most blocks in Minecraft 1.8.1. The oldest version supported is Minecraft Beta 1.3, in which the current world format was intorduced. Older versions of Minecraft use a different format that is not supported.

Chunky supports Minecraft from Beta 1.3. 

After some experimentation I think the word "Beta" is wrong. Beta 1.3 changed Alpha file format to Region file format. Unless I was just unlucky with the files I tried, it seems Chunky only supports Anvil file format which was introduced in Minecraft full release version 1.2.1.

---

2. Also "intorduced" should be "introduced".

:)

**Comment by llbit** [comment]
Thank you, I've updated the page to fix those issues: https://github.com/llbit/chunky-docs/commit/ea93efabcc95f647e8e75eea4481e6b2cece20a6
