### ISSUE TITLE
How soon will be updated to 1.13.2?!😬

### ISSUE THREAD

**Issue by Vlad0Crystal** [llbit/chunky#505]
Whenever I load a map into a piece, it just shows black. How soon will be updated to 1.13.2. I am ready to develop financially!

**Comment by Vlad0Crystal** [comment]
> Всякий раз, когда я загружаю карту в кусок, она просто показывает черный. Как скоро будет обновление до 1.13.2. Я готов развиваться в финансовом отношении!

Donat I meant 💲

**Comment by llbit** [comment]
I'm working on this now. I don't know how long it will take, but I will spend most of the weekend working on it.
