### ISSUE TITLE
How Can I fix it?

### ISSUE THREAD

**Issue by OngMong** [llbit/chunky#506]
![image](https://user-images.githubusercontent.com/38278609/52393401-39fae000-2ae9-11e9-9a2b-ce07c8e40ca4.png)

It doesn't understand my server maps

**Comment by EmeraldSnorlax** [comment]
it seems like you didn't download enlogu chunks! world download mod only downloads chunks in a 5 chunk radius so you have to run around to download the chunks

**Comment by chland** [comment]
What minecraft-version is the server running? Chunky only works with Minecraft 1.12 or older. Any newer versions won't work.

**Comment by OngMong** [comment]
@chland
1.13.2.
Then Can I downgrade it?

**Comment by chland** [comment]
As far as I know, its not possible to downgrade maps from 1.13+ to any earlier version  downgrading has never really been a thing and with the fundamental changes in 1.13, it would be a total nightmare.

**Comment by leMaik** [comment]
While downgrading isn't an option, 1.13+ support has been added in Chunky 2.0 so this is no longer an issue.
