### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by llbit** [llbit/chunky#512]
Chunky should have a dark GUI. Most other rendering software uses dark GUI themes and personally I always prefer dark GUIs.

This could be implemented by using JavaFX CSS.

**Comment by chland** [comment]
In case you ever want to create "Chunky 2" - I've got quite a few ideas for a complete redesign of the GUI/Workflow :)

**Comment by llbit** [comment]
@chland I've been wanting to redesign the UI and make Chunky single-window. Like 3ds Max or Blender, sort of.

**Comment by chland** [comment]
Yeah, a few months ago i messed around with Blender for a bit and that lead to me thinking about a Chunky redesign, too.

And another thing that came into my mind was to base Chunky around "projects". IDK if that is actually how other people work but often I find myself using the same chunk-selection for different scenes. So I thought it would be great if Chunky would allow you to create a "project". A project in this context would be a chunk-selection and a bunch of global scene-settings (that can be overwritten by individual scenes) like paths, render-resolution, texture-pack, etc. - inside of a project you can then create different scenes which all share the chunk-selection but stuff like camera-position, lighting, etc. can be different.
