### ISSUE TITLE
[Feature] Show a warning if an incompatible world is opened

### ISSUE THREAD

**Issue by chland** [llbit/chunky#519]
It would be nice if Chunky would display a warning if you try to open an incompatible world. So if you want to open a pre 1.13 world, a dialog should pop up saying something like "Sorry, but this version of chunky is only able to load worlds that were created in Minecraft 1.13 or later. If you want to open a world created with an earlier version of minecraft, please use Chunky 1.4.x or convert your world to the new format using a current version of Minecraft."

And IDK if you want to release one final 1.4.x verison, but it would be nice if the same kind of dialog would be shown there, too if you try to open a 1.13 or later world.

**Comment by Abequinn** [comment]
I'm pretty sure that llbit wants to maintain backwards compatibility with pre 1.13 (see #518)
