### ISSUE TITLE
Banners and Glazed Terracota show up wrong

### ISSUE THREAD

**Issue by EmeraldSnorlax** [llbit/chunky#520]
> Opened on behalf of Julius

- Banner colours appear really off;
![Banner](https://cdn.discordapp.com/attachments/545374333883777037/563056014857863209/Screenshot_164.png)
How it was rendered - How it is meant to look

- Glazed Terracota looks like it has the texture of smooth stone, also shows up in bottom of the preview window as Smooth Stone
(no image provided)

**Comment by llbit** [comment]
What Chunky version is this happening in?

**Comment by llbit** [comment]
This problem is caused by Mojang changing the color IDs for banner patterns in Minecraft 1.13.
