### ISSUE TITLE
Can't allocate custom amounts of memory

### ISSUE THREAD

**Issue by EmeraldSnorlax** [llbit/chunky#521]
Can't allocate custom amounts of memory in the launcher other then 1,024MiB

`C:\Program Files (x86)\Java\jre1.8.0_201\bin\java.exe -Xmx2048m -Dchunky.home=C:\Users\snorl\.chunky -classpath C:\Users\snorl\.chunky\lib\chunky-core-1.4.5.jar;C:\Users\snorl\.chunky\lib\commons-math3-3.2.jar se.llbit.chunky.main.Chunky`
causes the launch to fail

Using Windows 10 64x (8GB 2400mhz x1 RAM installed)

**Comment by mruk** [comment]
Terminal: `java -version`
and check if You are using 64-Bit build

**Comment by leMaik** [comment]
`C:\Program Files (x86)\Java\`, so this is 32-bit Java.

For future readers: To allocate more than ~2 GB of memory, use 64-bit Java.
