### ISSUE TITLE
Tripwires are invisible in render.

### ISSUE THREAD

**Issue by Lohfrum-Faleign** [llbit/chunky#522]
Attempting to make telephone poles with 'electrical wires' strung between them. In game, they're faint but visible, but they are invisible in render. I even attempted making them visible by altering their properties to become faint emitters. Still nothing.
![Flat World Big Tree Test12-30000](https://user-images.githubusercontent.com/49575771/56072818-17937600-5d69-11e9-9158-499a9427b6ba.png)

**Comment by leMaik** [comment]
This will be fixed in the next Chunky 2.0 snapshot.
