### ISSUE TITLE
Typing in input boxes makes the camera move in the render preview (2.0alpha10)

### ISSUE THREAD

**Issue by EmeraldSnorlax** [llbit/chunky#524]
Typing into any input field and pressing a directional key (WASD, Q, E, etc) also moves the camera around in the preview 

Edit: also happens on the map view
https://cdn.discordapp.com/attachments/541221265512464397/582191304306589741/2019-05-26_13-59-40.mp4

**Comment by llbit** [comment]
This was fixed in 2.0-beta3.
