### ISSUE TITLE
2.0/2.1 Underwater Emitters don't illuminate blocks correctly

### ISSUE THREAD

**Issue by jackjt8** [llbit/chunky#528]
Underwater emitters do not illuminate blocks and only illuminate the water surface. I have yet to test other conditions.

**Expected results (1.4.6beta2) -** 
![superflat_1 12_uw_emitters-1024](https://user-images.githubusercontent.com/3740917/58827688-825f8000-863b-11e9-9a81-2a217287a410.png)

**Results from 2.0beta2 -** 
![superflat_1 13_uw_emitters-1024](https://user-images.githubusercontent.com/3740917/58827917-1f221d80-863c-11e9-83dd-3657cd1dcba4.png)

Credit to _Lohfrum_Faleign_ for discovering this.

**Comment by jackjt8** [comment]
I have now tested with the camera above the waters surface, with the emitter being below, and I am seeing the same issue.

**Expected results (1.4.6beta2) -**
![superflat_1 12_uw_emitters2-1024](https://user-images.githubusercontent.com/3740917/58829192-2dbe0400-863f-11e9-8f91-404388d28309.png)


**Results from 2.0beta2 -**
![superflat_1 13_uw_emitters2-1024](https://user-images.githubusercontent.com/3740917/58828902-63162200-863e-11e9-999e-10951052e9c0.png)

**Comment by llbit** [comment]
I tried to reproduce this in 2.0-beta5 but it seems like a glowstone emitter works fine underwater.

**Comment by jackjt8** [comment]
It appears my initial assessment of the problem was incorrect. After testing 2.0beta5 in real time I noticed that emitters do in fact emit light but it is significantly reduced in both amounts and intensity. This prompted additional testing at 16SPP.

For a camera which is submerged (test 1), it's not just the emitter which are seeing diminished effectiveness, but also the sunlight itself. In the case of the camera being above the water (test 2), sunlight appears to work as normal but the issue with the emitter remains.

**Test 1**
1.4.6beta2
![superflat_1 12_uw_emitters-16_146b2](https://user-images.githubusercontent.com/3740917/59152629-110b3d00-8a40-11e9-976b-2bea4540a556.png)

2.0beta4/5
![superflat_1 13_uw_emitters-16_2b5](https://user-images.githubusercontent.com/3740917/59152636-22544980-8a40-11e9-9e43-91a3a7c74b09.png)

2.0beta4/5 (increased brightness)
![superflat_1 13_uw_emitters-16_2b5+bright (2)](https://user-images.githubusercontent.com/3740917/59152642-4c0d7080-8a40-11e9-8193-721e68932aeb.png)

**Test 2**
1.4.6beta2
![superflat_1 12_uw_emitters2-16_146b2](https://user-images.githubusercontent.com/3740917/59152653-8aa32b00-8a40-11e9-8baa-3f0f31388174.png)

2.0beta4/5
![superflat_1 13_uw_emitters2-16_2b4](https://user-images.githubusercontent.com/3740917/59152659-a3134580-8a40-11e9-941f-2667d6ca9b36.png)

**Comment by jackjt8** [comment]
I also decided to generate another 1.12 world with an Ocean Monument and port it into 1.13. I matched the settings otherwise- This time having emitter intensity set to 1000, but I'm certain the same is true for sunlight, I will just test that in a second.

1.4.6beta2
![Ocean12-128](https://user-images.githubusercontent.com/3740917/59152839-3e59ea00-8a44-11e9-9e72-67cb121a8855.png)

2.0beta5
![default-128](https://user-images.githubusercontent.com/3740917/59152841-43b73480-8a44-11e9-9fb5-e42577364730.png)

**Comment by jackjt8** [comment]
And finally just some testing of the sun light under water. Intensity set to 5.

1.4.6beta2
![Ocean12-128_sun](https://user-images.githubusercontent.com/3740917/59152879-2f276c00-8a45-11e9-9ebf-55922961fa35.png)

2.0beta5
![default-128_sun](https://user-images.githubusercontent.com/3740917/59152880-33538980-8a45-11e9-920b-edf5516cfd9e.png)

**Comment by llbit** [comment]
Thanks for the update, I'll continue to investigate. Could you upload the scenes for Test1?

**Comment by jackjt8** [comment]
[Test_1.zip](https://github.com/llbit/chunky/files/3269734/Test_1.zip)

Certainly. I've also provided the original worlds just in case you would want them.

**Comment by jackjt8** [comment]
Did some additional testing and noticed that for non-flush light sources underwater light propagates at least 1 block in each direction like it does in 1.4.5.

1.4.5
![NoiseTest_b_1_water_glass-256](https://user-images.githubusercontent.com/3740917/80516833-03beb000-897c-11ea-8c34-4a2d0c46c286.png)

2.0beta6
![NoiseTest_b_2_water_glass-256](https://user-images.githubusercontent.com/3740917/80517047-5ac48500-897c-11ea-9198-771114b21fdd.png)
