### ISSUE TITLE
2.0beta4 Loading scene with emitters enabled (not rendering) breaks emitters

### ISSUE THREAD

**Issue by jackjt8** [llbit/chunky#529]
If a emitters are enabled in `2.0beta4` and the scene is saved without starting the render, when the scene is loaded, and the render is started, the emitters will act as if they are disabled. Toggling `Enable emitters` on/off or changing the `Emitter intensity` does not fix this. The only solution (so far) is to delete the scenes `.dump`, `.foliage`, `.grass`, and `.octree` prior to loading the scene which allows them to be remade.

**Expected result after loading and rendering a scene:**
![image](https://user-images.githubusercontent.com/3740917/58816567-a7df9000-8621-11e9-9501-5f59c8f39d41.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/3740917/58831130-e128f780-8643-11e9-81e0-50e5ebc5e71b.png)

Credit to _Lohfrum_Faleign_ for discovering this.

**Comment by llbit** [comment]
This looks like a bug with material properties not being correctly applied to the block palette after loading a saved scene.

**Comment by llbit** [comment]
Fixed in 2.0-beta6.
