### ISSUE TITLE
Chunky loading all chunks as ocean.

### ISSUE THREAD

**Issue by Dertanious** [llbit/chunky#530]
Also when I generate a preview there is nothing there.

**Comment by D-04** [comment]
Can you give us more information like the version of chunky you are running, the version of the minecraft world you loaded and if you have loaded any texture packs?

**Comment by Dertanious** [comment]
Chunky 1.4.5, Minecraft 1.14.2 and I don't have any texture packs

**Comment by D-04** [comment]
As far as I know chunky does not support 1.14 maps yet.

**Comment by Dertanious** [comment]
Oh. I'll have a try on a 1.13 map now

**Comment by D-04** [comment]
Can you give us an update on whether it is working or not so we can potentially close this issue.

**Comment by Project579** [comment]
I don't think Chunky supports the new save format, 1.13 saves do not work, I get an empty world with ocean everywhere and some random flat world pieces, also clicking on Nether makes chunky crash (if using 1.13 save or newer).

**Comment by jackjt8** [comment]
Chunky 1.4.5/1.4.6beta2 only support mc 1.12 worlds.

For mc 1.13 support you will need to try the Chunky 2.0 Beta which requires an updated launcher and download server. [Please visit the Chunky 2.0 page for information and how to set it up](http://chunky.llbit.se/chunky2.html).
