### ISSUE TITLE
"Error in opening zip file" in chunky resource packs

### ISSUE THREAD

**Issue by BLeAToKID19** [llbit/chunky#531]
Hi, I m new in chunky and I dont know how to load a resource pack yet. But even following exactly steps in other issues, I get a warning saying: "Error in opening zip file". Thanks in advance.
![Capture](https://user-images.githubusercontent.com/51421752/58987840-ac9e7280-87e0-11e9-9c8f-4dfd4a34cab1.PNG)

**Comment by D-04** [comment]
It appears you are using an older version of chunky. You need to update chunky by selecting the "latest" version in the chunky launcher and pressing update. If it doesnt work after you tried this, please give us more information like the minecraft version of the World aswell as the version of the texturepacks.
![2313121234](https://user-images.githubusercontent.com/51401275/58988229-79101800-87e1-11e9-81a7-0d61da8a8f28.PNG)

**Comment by BLeAToKID19** [comment]
> It appears you are using an older version of chunky. You need to update chunky by selecting the "latest" version in the chunky launcher and pressing update. If it doesnt work after you tried this, please give us more information like the minecraft version of the World aswell as the version of the texturepacks.
> ![2313121234](https://user-images.githubusercontent.com/51401275/58988229-79101800-87e1-11e9-81a7-0d61da8a8f28.PNG)
My chunky version is the latest 1.4.5, with 1.12.2 minecraft and resource pack

**Comment by EmeraldSnorlax** [comment]
Does the pack follow the normal vanilla pack structure?
ie pack/assets

seems to me like its not
try loading a different texturepack and see if the issue still happens

**Comment by BLeAToKID19** [comment]
> Does the pack follow the normal vanilla pack structure?
> ie packName/assets/[textures]
> 
> seems to me like its not
> try loading a different texturepack and see if the issue still happens

I downloaded Faithful rv4 and made it in the right structure, but I get the same warning :(

**Comment by EmeraldSnorlax** [comment]
if loading a different pack still causes this issue, its likely a bug

try the chunky discord https://discord.gg/nf5YKd4

**Comment by BLeAToKID19** [comment]
> if loading a different pack still causes this issue, its likely a bug
> 
> try the chunky discord https://discord.gg/nf5YKd4

Okay.. Thanks anyway

**Comment by llbit** [comment]
@BLeAToKID19 could you post a link to a resource pack which gives you this error? That would really help in fixing the issue.

**Comment by BLeAToKID19** [comment]
That's the used resource pack (sorry for being too late)[https://www.curseforge.com/minecraft/texture-packs/faithful-32x/download/2480942](url)

**Comment by leMaik** [comment]
That resource pack works fine now... Maybe the zip file was corrupted?
