### ISSUE TITLE
Auto centering camera after Move camera here has been used

### ISSUE THREAD

**Issue by jackjt8** [llbit/chunky#532]
Small issue following the move to the one Windows UI and a certain commit to fix an issue; Specifically the following commit: https://github.com/llbit/chunky/commit/92b2ca908c772be2287a058388b2ee39f3a550a5

And this section:

```
      if (prevChunkCount == 0) {
        scene.moveCameraToCenter();
      }
```

Given a scene is open by default, we have access to the `Map` right click option `Move camera here` from the get go however, if this action is performed prior to loading any chunks per the commit above the camera position would be centered. This goes against past decisions to have `Load selected chunks` not move the camera once set (#154).

Would request a check is made to see if `Move camera here`  has been used, else Center camera.

**Comment by llbit** [comment]
I think the issue with not centering the camera when clicking `Load selected chunks` is that it may be confusing for new users who have to then orient the camera to find the loaded chunks.

The check `if (prevChunkCount == 0)` will avoid moving the camera if new chunks are loaded into a scene that already has some loaded chunks. I wonder how common it is to position the camera before loading any chunks.

**Comment by jackjt8** [comment]
I understand the reason for it to work the way it does currently.

This does appear to be a fringe case as I only know one person who uses 'Move camera here' prior to loading the Chunks so this might not be cause for concern.

I'll close this issue for now.
