### ISSUE TITLE
Chunky loading as ocean

### ISSUE THREAD

**Issue by ThatTurtleGamer** [llbit/chunky#533]
I'm running Chunky version 1.4.5, Minecraft version 1.14.2 and tried it on 1.13, nothing is rendering and what it does render is blue. Does anyone know any fixes?
![image](https://user-images.githubusercontent.com/51763806/59385979-2d062b80-8d2b-11e9-963a-142447334b3d.png)

**Comment by EmeraldSnorlax** [comment]
Only the beta can render 1.13.2

1.14 isnt officially supported

**Comment by ThatTurtleGamer** [comment]
@EmeraldSnorlax ok thanks

**Comment by ThatTurtleGamer** [comment]
@EmeraldSnorlax where is the 1.11 launcher download?

**Comment by EmeraldSnorlax** [comment]
Chunky website -> download -> click launcher only jar

**Comment by ThatTurtleGamer** [comment]
@EmeraldSnorlax still doing the same thing

**Comment by EmeraldSnorlax** [comment]
sounds like your browser has cached the old download

try downloading in a private tab / clearing cache, cookies etc / using a different browser

**Comment by ThatTurtleGamer** [comment]
@EmeraldSnorlax nope nothing changed, do the settings look correct?
![Untitled-1](https://user-images.githubusercontent.com/51763806/59387798-ad2e9000-8d2f-11e9-8757-ff0d48d01504.png)
![Untitled-2](https://user-images.githubusercontent.com/51763806/59387809-b15aad80-8d2f-11e9-9880-002225452357.png)

**Comment by ThatTurtleGamer** [comment]
@EmeraldSnorlax oh nvm got it, I had an update to do thx
