### ISSUE TITLE
Chunky no chunks loading

### ISSUE THREAD

**Issue by ThatTurtleGamer** [llbit/chunky#534]
Do I have to explore the whole map for it to load? 
![image](https://user-images.githubusercontent.com/51763806/59399883-39a27800-8d5b-11e9-87d8-e8f837d68f6a.png)

**Comment by EmeraldSnorlax** [comment]
Yes, in Minecraft

**Comment by ThatTurtleGamer** [comment]
@EmeraldSnorlax Does the entire map have to be loaded? Whenever I preview nothing shows up but void.
