### ISSUE TITLE
Chunky alpha 2.0 / Instead of panes, fences and iron bars I get blue questionmarks?!

### ISSUE THREAD

**Issue by VMark5** [llbit/chunky#537]
I'm not sure if this is a bug or i'm doing something wrong, but help would be appreciated. I got the Chunky 2.0 because I wanted to render a 1.14 world. When I tried to use the 1.4.5 it couldn't load the world so it was just white with some outlines. When I got the 2.0 it finnaly worked, I enabled the custom texture pack that I used with the world (1.14 ready) and flew around with the render preview thing and all of the full sized blocks were fine and good looking but all these thin blocks like walls, iron bars, glass panes and fences were missing and instead of them there were blue questionmarks. I also tried a different world with the default MC texture pack and the same problem accured.
![Chunky Render](https://user-images.githubusercontent.com/52828518/61134710-7b405300-a4c0-11e9-945d-ed2840ccb771.png)
 I really need that render so any help would be welcome. Thank you :)

P.S. I included a picture to show what I'm having an issue with.

**Comment by EmeraldSnorlax** [comment]
1.13 is still in beta, 1.14 support is a side-effect of 1.13 world loading. For now, you'll have to wait for Chunky2 to release

**Comment by devedse** [comment]
@EmeraldSnorlax I was also running into this issue. Is there an ETA on the Chunky2 release?

**Comment by EmeraldSnorlax** [comment]
ask llbit lol

**Comment by devedse** [comment]
@llbit do you have an update on this :)?

**Comment by jackjt8** [comment]
Alpha 2.0?

What version of Chunky are you using?

**Comment by devedse** [comment]
I'm using Alpha 2.0 for minecraft 1.14 and was also running into the question mark blocks

**Comment by jackjt8** [comment]
Chunky 2.0 alpha2? Or what?

Chunky 2.0 is currently at version beta6 so you probably need to update and retest.

**Comment by devedse** [comment]
@jackjt8 I used the MinecraftLauncher to download alpha 2:

![image](https://user-images.githubusercontent.com/2350015/61955125-a8116180-afba-11e9-965d-d4aaa168762b.png)

How would you go about updating to beta 6?

**Comment by jackjt8** [comment]
Assuming the ChunkyLauncher has snapshots enabled and the correct download server, being http://chunkyupdate2.llbit.se/ , the newer version will show up.

For more information check the official webpage on Chunky 2.0: http://chunky.llbit.se/chunky2.html

**Comment by devedse** [comment]
@jackjt8 , the issue was that I did not have Download Snapshots enabled. Thanks for the advice :smile:.

The map seems to not load though:
![image](https://user-images.githubusercontent.com/2350015/61974111-0dc71300-afe6-11e9-9661-fabd505f83bb.png)

It's a map I created in Minecraft 1.14

**Comment by jackjt8** [comment]
Chunky 2.0 only officially supports Minecraft 1.13. 1.14 is a side effect. The map view won't work but chunks should load normally.

**Comment by devedse** [comment]
@jackjt8 , I tried selecting all chunks but the render preview shows a white ground with basically nothing on it.

![image](https://user-images.githubusercontent.com/2350015/61978188-e0339700-aff0-11e9-9a6b-cd982f55d2fa.png)

I guess I'll wait for 1.14 to be supported then.

**Comment by jackjt8** [comment]
Click _Load selected chunks_ over on the left once selected in map view.

**Comment by Givemeausernamethatisavailable** [comment]
After a very long time, I decided to have a look how far Chunky 2 already is and installed it yesterday - and I have exactly the same problem.
I tried everything that was suggested in this thread. But nothing worked.
Actual Minecraft version is 1.15.1, Chunky version is 2.0-alpha2
![Planet Sauvage-1000](https://user-images.githubusercontent.com/59478841/71729013-fb77bd80-2e3e-11ea-981f-d22e0dc5af56.png)

**Comment by jackjt8** [comment]
Would you be able to screenshot your launcher just to confirm everything is setup correctly?

Either way, I can provide a mirror of files needed for Chunky 2.0beta2 - https://drive.google.com/folderview?id=1lMVNpbJMQbtlm9m0G3-A2tw0uSD_7McS
