### ISSUE TITLE
Chunky not opening once installed

### ISSUE THREAD

**Issue by Etomic-Studios** [llbit/chunky#538]
I have just started using chunky for some builds but once I installed it, nothing appears. Not even a windows opens up. I am running version 1.4.5 and have tried the universal and windows installer. I am running on windows 10. What do I do?

**Comment by EnneaX** [comment]
Hey,
are you trying to start it by double-clicking the icon?
If so, you could try to start it by using the terminal:
Start your commandline and navigate to the chunky install folder.
Then type:
`java -jar chunky.jar`

Let us know if this fixes things for you.

**Comment by TheDeadlyOctopus** [comment]
I've been having the same issue when I run that command I get this error "Error: Unable to access jarfile chunky.jar" (I'm using java JRE 8u221)
