### ISSUE TITLE
Maybe not new but I had to ask

### ISSUE THREAD

**Issue by MrKiller01** [llbit/chunky#539]
This is a request:    (Compliments for this great program)
In my search for updating our almost 5 years old 1.13.2 worlds up to the latest 1.14.4 version, I stumbled upon your fantastic program. I was only concerned when I tried a little on a local copy of that 14 GB size world, it makes the area I selected nice and neat but it also removes all builds there... 
That was my point, what happens to everything under the surface, is that also back to normal? because then either it is not usable for builds with above and under the surface buildings, and even where tunnels/trains etc. are going under an ocean or river will be gone too. 
So, i'm thinking, is it possible to leave all builds in a selected chunk untouched by Chunky? or is that absolutely not possible?
Then maybe alter the plugin to a server utility, let serveradmins fly over areas he / she thinks that needs rebuilding, select a surface area and do re-render...
Or am I fantasizing too much?

**Comment by MrKiller01** [comment]
No comment, but can you please give Chunky the possibility to replace deleted chunks from backup file??
It is so troubling that when I find out I accidently removed a bit, I can't get it to restore without the server crashing once and a while..... I think it is better to do it in Chunky than in the world itself...

**Comment by MrKiller01** [comment]
and I thought that you were keen on answering and being helpful.... well, then it must be Real Life that came in between.....
If you happen to see this post, please let me know if there is such a possibility, because no way in ... that I'm gonna restore surface without really knowing what is beneath the surface.....   A real shame Mojang did not account for this problem to prevent into their software....

**Comment by 073TheBoss** [comment]
Unless you hit the "Delete Selected Chunks" button, the world file shouldn't be modified by Chunky. I'm not sure if it's active anymore or not, but MCEdit can be used to replace deleted chunks from backups.

**Comment by EmeraldSnorlax** [comment]
i think you've kinda misunderstood what chunky is @MrKiller01. Chunky is used for rendering, not for edifying chunks, updating chunks, etc

**Comment by MrKiller01** [comment]
> i think you've kinda misunderstood what chunky is @MrKiller01. Chunky is used for rendering, not for editing chunks, updating chunks, etc
> 
> Also this program isn't made by mojang lol

That last remark.... OMG I DID NOT KNOW.... Seriously? You thought that I did not know that?
To make this reply short, is deleting chunks not the same as editing? edit https://en.wikipedia.org/wiki/Editing
and FYI, my question you did NOT answer, did not help here...
Thanks

> Unless you hit the "Delete Selected Chunks" button, the world file shouldn't be modified by Chunky. I'm not sure if it's active anymore or not, but MCEdit can be used to replace deleted chunks from backups.

And your reply was usefull @073TheBoss but what is wrong with my question? we don't have to go to Word to type things in a document and then go to Corel or any other typing program that can change what I just typed.... Now that would be silly, isn't it? It is half finished.
If Chunky has the power to delete complete sections of a map, why not give the power to restore it by backup or just saved to zip file?

**Comment by leMaik** [comment]
The main goal of Chunky is being a path tracer to render beautiful images of Minecraft worlds, so I'll close this as _Won't fix_. The ability to delete chunks is already implemented, but restoring chunks from backups seems to be out of scope – there are already other programs that can do this.

**Comment by sn0wyfall** [comment]
@MrKiller01 Please note that the developer (to my knowledge) does not get paid for developing this program. As such, please don't demand the addition of any features, even if they seem like an obvious thing to implement—it is kind of rude.
