### ISSUE TITLE
Terracottas texture isnt shown in chunky

### ISSUE THREAD

**Issue by browniescooter** [llbit/chunky#540]
I tried to create a render of a building but the terracotta texture has no texture. Its a black block with a red cross on it. What can I do to get the real terracotta texture?

**Comment by EmeraldSnorlax** [comment]
load a texturepack for the corresponding version

**Comment by browniescooter** [comment]
a bit stupid, I created a resource pack with the same textures as the default pack. And it works perfectly. stupid stupid
