### ISSUE TITLE
Chunky on macOS 10.15 - Unable to load Java Runtime Environment

### ISSUE THREAD

**Issue by liam-b** [llbit/chunky#545]
I tried using chunky by downloading the dmg and running the application and just receive the error in a popup dialog box: `Unable to load Java Runtime Environment`. 

Java doesn't come preinstalled with Catalina so I've installed openjdk. Running `java -version` returns:
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
```

`which java` returns: `/usr/bin/java`, and my PATH is: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin`

Is this a problem with Catalina?

**Comment by TheRealJayjayli** [comment]
May be just you, I'm running macOS Catalina 10.15.1 with Chunky 2.0. Did you download java from https://www.java.com/en/download/mac_download.jsp ?

**Comment by EmeraldSnorlax** [comment]
Use Oracle Java.

**Comment by liam-b** [comment]
Yep, that seems to have fixed it. Thanks, guys.
