### ISSUE TITLE
Some diagonal banners designs are mixed up

### ISSUE THREAD

**Issue by jackjt8** [llbit/chunky#552]
Minecraft 1.14.4

"Per Bend Sinister Inverted Banner" is rendered as "Per Bend Banner" in Chunky and vice versa. - See the [Minecraft Wiki for Banners under "Halfs"](https://minecraft.gamepedia.com/Banner_Pattern).

![image](https://user-images.githubusercontent.com/3740917/78992661-aaf5b780-7b33-11ea-94b4-6259c431978d.png)

**Comment by leMaik** [comment]
This will be fixed in the next snapshot.
