### ISSUE TITLE
Chest texture incorrect

### ISSUE THREAD

**Issue by 073TheBoss** [llbit/chunky#564]
The texture for the top and bottom parts of the chest is upside down. This is the latest leMaik snapshot as of April 16, 2020.

Chest in latest Chunky snapshot: 
![javaw_2020-04-15_20-37-31](https://user-images.githubusercontent.com/30638248/79509812-e0057c80-8001-11ea-806b-1a2ad9689ac0.png)

Chest in Minecraft 1.15.2: 
![mcChest](https://user-images.githubusercontent.com/30638248/79509843-f0b5f280-8001-11ea-8275-c728fc5b8b74.png)

**Comment by leMaik** [comment]
This was changed in 19w39a. Unfortunately, just fixing this would break 1.13 and 1.14 compatibility.
