### ISSUE TITLE
2.0/2.1 Increased memory usage compared to 1.X

### ISSUE THREAD

**Issue by jackjt8** [llbit/chunky#576]
Changes made to provide support for Minecraft 1.13 in Chunky 2.X have significantly increased the amount of memory used compared to Chunky 1.4.5.

| Version  | Max Chunks with 16GB allocation | Reduction (1.X) |
|----------|---------------------------------|-----------------|
|          | with 540p canvas                |                 |
| 1.4.5    | 50,000                          | 0%              |
| 2.0beta6 | 20,000                          | 60%             |
| 2.1-282  | 20,000                          | 60%             |

I should note that with a more typical canvas size of 2160p, skymaps, etc. Actual Max Chunks will be about half of what is listed above. (ie 1.4.5 max ~25k, 2.X max ~10k)

**Comment by 073TheBoss** [comment]
Any update on those numbers after 2.2? I think this issue can be closed because of the octree optimizations made by aTom3333, which reduced memory usage.

**Comment by jackjt8** [comment]
Forgot to update this thread with the updated numbers after the nightly snapshot.

The Packed Octree results in about a 40% increase in the number of chunks we can load over 1.4.5 and.. well.. 2.X Legacy just doesn't compare.

|1.4.5|2.X legacy|2.X packed|
|:-|:-|:-|
|\~82k|\~33k|\~115k|
_28GB Allocation_
