### ISSUE TITLE
403 Error when trying to "-download-mc" 1.13 or higher

### ISSUE THREAD

**Issue by itsCryne** [llbit/chunky#578]
When trying to download a minecraft version greater or equal to 1.13 on a headless server with `-download-mc <version>` the AWS server always returns a 403, downloading minecraft below 1.13 seems to work fine:
```
java -Dchunky.home="chunky" -jar ChunkyLauncher.jar -download-mc 1.13.2
Downloading Minecraft 1.13.2...
url: https://s3.amazonaws.com/Minecraft.Download/versions/1.13.2/1.13.2.jar
destination: /home/<user>/chunky/resources/minecraft.jar
Download failed (Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.13.2/1.13.2.jar)
```

```
java -Dchunky.home="chunky" -jar ChunkyLauncher.jar -download-mc 1.12.2
Downloading Minecraft 1.12.2...
url: https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar
destination: /home/<user>/chunky/resources/minecraft.jar
Done!
```

Kind regards from germany.

**Comment by leMaik** [comment]
Good thing I already fixed the same bug in a related project: https://github.com/leMaik/ChunkyMap/commit/0b33438f656e5c33da5fc7ed74e2b8710f7841b0

This will be fixed in the next Chunky version. :+1:
