### ISSUE TITLE
chunky with world downloader

### ISSUE THREAD

**Issue by Leikonka** [llbit/chunky#589]
Hello, I downloaded building from server via world downloader both version 1.14.4, and when I was trying to render it in chunky its just big back map and its not even loading preview in that big screen.
From official website I downloaded windows installer chunky 1.4.5, but I didnt found 1.14.4 version if that could be the problem. Do im just totaly blind, or its some other problem?
![chunky1](https://user-images.githubusercontent.com/51082150/82055669-2281ae00-96c1-11ea-9885-c516ef03f84a.png)

**Comment by jackjt8** [comment]
Chunky 1.4.5 is for Minecraft 1.12.2.

For opening Minecraft 1.13+ worlds, as the world format is different, you need to instead use the ChunkyLauncher with the correct update site as you need to get Chunky 2.

[leMaik's Chunky is the only way to load 1.14+ blocks and is the new way to update](https://chunky.lemaik.de/installation) .

**Comment by Leikonka** [comment]
> 
> 
> Chunky 1.4.5 is for Minecraft 1.12.2.
> 
> For opening Minecraft 1.13+ worlds, as the world format is different, you need to instead use the ChunkyLauncher with the correct update site as you need to get Chunky 2.
> 
> [leMaik's Chunky is the only way to load 1.14+ blocks and is the new way to update](https://chunky.lemaik.de/installation) .

thank you, problem solved
