### ISSUE TITLE
Issues starting Chunky

### ISSUE THREAD

**Issue by coolduucks** [llbit/chunky#617]
Chunky Won't run and I've reinstalled both java and chunky. When I attempt to run the launcher it won't show up in task manager.

**Comment by coolduucks** [comment]
Oh also It's the latest version of windows 10 and java

**Comment by jackjt8** [comment]
Common issue with Java on Windows. Open command prompt and check to see if `Java -version`  returns anything or is an unrecognised command.

If that works we have a few options:

---

1. Get the path to ChunkyLauncher.jar, ie _D:\Programs\Chunky_, and then open _command prompt_.

```
cd p:\ath\to\ChunkyLauncherjar
java -jar ChunkyLauncher.jar --launcher
```

1b. Next to ChunkyLauncher.jar Right Click > New > Text Document. Paste the following:

```
cd /d %~dp0
java -jar ChunkyLauncher.jar --launcher
```

File > Save As - File name: whateveryouwant.**bat** (opposed to whateveryouwant.txt). You can then  double click the .bat file to run Chunky.

---

2. Run something like [JarFix](https://johann.loefflmann.net/en/software/jarfix/index.html) and then just double click the .jar as normal.

**Comment by filips123** [comment]
I have the same issue on Windows 10. Java is installed and added to path:

```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

Running `ChunkyLauncher.jar` from CMD causes this error:

```
$ java -jar ChunkyLauncher.jar --launcher
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javafx/stage/Stage
        at se.llbit.chunky.launcher.ChunkyLauncher.firstTimeSetup(ChunkyLauncher.java:274)
        at se.llbit.chunky.launcher.ChunkyLauncher.main(ChunkyLauncher.java:192)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/Stage
        ... 2 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.Stage
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more
```

**Comment by coolduucks** [comment]
Ok I got it working with Jarfix, thank you :)

**Comment by jackjt8** [comment]
filips123, that is a different issue so either open a new issue or search for the fix.

OpenJDK 8 on Windows does not come with the require JavaFX modules. Switch back to Oracle Java or you can either build OpenJFX or just grab the precomiplied [files say here](https://github.com/SkyLandTW/OpenJFX-binary-windows/releases).

**Comment by coolduucks** [comment]
nevermind it broke again
:(

**Comment by leMaik** [comment]
@coolduucks What exactly broke again? Do you get any error messages?

As explained above, your error messages suggested that JavaFX was missing.

**Comment by leMaik** [comment]
@coolduucks I'll close this for now. Please re-open or join our discord so we can help you run Chunky. :-)
