### ISSUE TITLE
Isometric View Cuts off part of selected chunks

### ISSUE THREAD

**Issue by MattQ012** [llbit/chunky#626]
I hope this is the right place to report a bug. When using the Isometric View for a render, part of the selection gets cut off and doesn't render. See this Image for reference: https://imgur.com/a/XysVj46

The Chunks will only get completely loaded if looking 90 Degrees down

**Comment by leMaik** [comment]
Thanks for reporting this bug. Unfortunately, I'm not able to reproduce it. Could you send me an entire scene with all related files where this issue occurs?

**Comment by leMaik** [comment]
@Lohfrum-Faleign solved it: This happens it the camera is too close to the ground in isometric view and thus clips into the ground. The solution is to move it up by pressing R (to move it up faster, press Ctrl+R).

Please let me know if this fixes it for you. :-)

**Comment by jackjt8** [comment]
While altering the camera height would solve the issue, it's not caused by the camera being too close to the ground in that sense. Moving the camera, in any direction, away from the ground solves this issue.
