### ISSUE TITLE
Empty scene folders

### ISSUE THREAD

**Issue by aTom3333** [llbit/chunky#639]
Every time i use chunky a new folder is created (named default-...) even when the scene is never saved. As such i end with a bunch of empty folders that aren't needed.
Chunky should wait for the user to actually save the scene before creating the folder

**Comment by leMaik** [comment]
Also scenes get saved to the wrong folder after renaming. I'll look into this.

**Comment by leMaik** [comment]
This should be fixed in the latest snapshot.
