### ISSUE TITLE
50% of chunks gone when creating new scene and can't load any more chunks

### ISSUE THREAD

**Issue by UAVwaffle** [llbit/chunky#648]
The attached screenshots show the issue.

When I first installed everything worked fine, then the next day I decide to make a even bigger render, that's when I first expirenced this bug.  Now it does not matter how much ram is allocated it does this and I can only make small renders (much smaller than what I could do before)  lastly when I try to make a new scene after it does this I get a error window that says, " warning,  can't load chunks right now" I get this box whenever I make a new scene until I restart the software.  I tried deleting and reinstalling chunky and even tried different versions (latest normal and latest snapshot) they both do this.

![Screenshot (407)](https://user-images.githubusercontent.com/68166007/88467326-fdb96c00-cea3-11ea-9da4-9cc5d52f69e8.png)
![Screenshot (406)](https://user-images.githubusercontent.com/68166007/88467327-fe520280-cea3-11ea-96bf-629ceb4b427c.png)

**Comment by UAVwaffle** [comment]
I forgot to add,   the red you see in the first screenshot's background does not seem to indicate this issue, I get the same bug(missing chunks) even if the background looks normal.

**Comment by leMaik** [comment]
Is this by any chance a world that was converted to 1.14 after being downloaded with WorldDownloader?

**Comment by leMaik** [comment]
@UAVwaffle A new snapshot with a fix for this is now available. Please let us know if it fixes the issue (either by opening a new issue or on Discord).
